### ISSUE TITLE
Domain join fails depending on instance type

### ISSUE THREAD

**Issue by galbinasu** [BeyondTrust/pbis-open#103] opened 2018-02-20 10:38 UTC
We are stuck with this ongoing issue when trying to join machines into our domain when using SUSE 12 SP2. For reference we are using AWS instances. We get errors reported in all instance types although it seems the machine is joined to the domain (not very encouraging though). However, for the X1 instance type the software fails altogether to join the domain. 

PBIS version: 8.5.7.385
OS version: SUSE Linux Enterprise Server 12 SP2
Command: domainjoin-cli --logfile /var/log/domain_join.log --loglevel info join --ou "#{ou}" #{domain} '#{user}' '#{pass}'

We run Domainjoin as part of a Chef cookbook, ran on an EC2 instances in AWS. 
On most instance sizes (t2.\*, m4.\*, r4.\*) the command is successful (although it reports error). 
On x1.\* instance types the command fails completely.

**Other instances types print this error (reports error but joins the domain)
/var/log/domain_join.log**

20180219164222:INFO:Domainjoin invoked with the join command (remaining arguments will be printed later):
20180219164222:INFO:    [domainjoin-cli]
20180219164222:INFO:    [--logfile]
20180219164222:INFO:    [/var/log/domain_join.log]
20180219164222:INFO:    [--loglevel]
20180219164222:INFO:    [info]
20180219164222:INFO:    [join]
20180219164222:INFO:Domainjoin invoked with option --ou OU=WE1-A1-CS01,OU=Alpha,OU=WE1,OU=DCTR,DC=CH2,DC=AD,DC=COM
20180219164222:INFO:Domainjoin invoked with 3 arg(s) to the join command:
20180219164222:INFO:    [ch2.ad.com]
20180219164222:INFO:    [-serv-chef-com-join]
20180219164222:INFO:    [<password>]
20180219164222:INFO:Adding we1a1cs010a95 (fqdn we1a1cs010a95.ch2.ad.com) to /etc/hosts ip 127.0.0.1, removing we1a1cs010a95, we1a1cs010a95.ch2.ad.com, we1a1cs010a95, localhost.localdomain
20180219164222:WARNING:A resumable error occurred while processing the 'hostname' module
ERROR_BAD_COMMAND [code 0x00000016]

20180219164222:WARNING:ERROR_BAD_COMMAND [ERROR_BAD_COMMAND]

Stack Trace:
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djhostinfo.c:1286
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djhostinfo.c:1526
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djhostinfo.c:1064
20180219164222:INFO:Running module keytab
20180219164222:INFO:Reading krb5 file /etc/krb5.conf
20180219164222:INFO:Writing krb5 file /etc/krb5.conf
20180219164222:INFO:File /etc/krb5.conf modified
20180219164222:INFO:Reading krb5 file /tmp/likewisetmpcp1Pth/etc/krb5.conf
20180219164222:INFO:Running module join
20180219164224:INFO:Running module nsswitch
20180219164224:INFO:Reading nsswitch file /etc/nsswitch.conf
20180219164224:INFO:Writing nsswitch configuration for /etc/nsswitch.conf
20180219164224:INFO:File moved into place
20180219164224:WARNING:System restart required
Your system has been configured to authenticate to Active Directory for the first time.  It is recommended that you restart your system to ensure that all applications recognize the new settings.


**Instance X1 Type Error (Doesn’t join the domain).
/var/log/domain_join.log**

20180219164904:INFO:Domainjoin invoked with the join command (remaining arguments will be printed later):
20180219164904:INFO:    [domainjoin-cli]
20180219164904:INFO:    [--logfile]
20180219164904:INFO:    [/var/log/domain_join.log]
20180219164904:INFO:    [--loglevel]
20180219164904:INFO:    [info]
20180219164904:INFO:    [join]
20180219164904:INFO:Domainjoin invoked with option --ou OU=WE1-A1-CS01,OU=Alpha,OU=WE1,OU=DCTR,DC=CH2,DC=AD,DC=COM
20180219164904:INFO:Domainjoin invoked with 3 arg(s) to the join command:
20180219164904:INFO:    [ch2.ad.com]
20180219164904:INFO:    [-serv-chef-com-join]
20180219164904:INFO:    [<password>]
20180219164904:INFO:Adding we1a1cs010a96 (fqdn we1a1cs010a96.ch2.ad.com) to /etc/hosts ip 127.0.0.1, removing we1a1cs010a96, we1a1cs010a96.ch2.ad.com, we1a1cs010a96, localhost.localdomain
20180219164904:INFO:Reading krb5 file /tmp/likewisetmp2QZYj2/etc/krb5.conf
20180219164904:INFO:Reading nsswitch file /etc/nsswitch.conf
20180219164904:INFO:Reading krb5 file /tmp/likewisetmpneohY3/etc/krb5.conf
20180219164904:INFO:Distro Version 12
20180219164904:INFO:Reading pam configuration
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/runuser
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-account
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-auth
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/systemd-user
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/userdel
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-password.pam-config-backup
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/su
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-password-pc
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-session
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/passwd
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/sudo
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/chage
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/remote
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/groupdel
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/chpasswd
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-account-pc
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-session-pc
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-auth.pam-config-backup
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/polkit-1
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-auth-pc
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/atd
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-session.pam-config-backup
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/useradd
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/usermod
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/screen
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-account.pam-config-backup
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/other
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/newusers
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/ppp
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/vlock
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/sshd
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/runuser-l
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/crond
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/groupadd
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/init
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/groupmod
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/common-password
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/chfn
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/login
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/su-l
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.d/chsh
20180219164904:INFO:Reading pam file /tmp/likewisetmp2mcTC5/etc/pam.conf
20180219164904:INFO:File /tmp/likewisetmp2mcTC5/etc/pam.conf does not exist
20180219164904:INFO:Found config file /etc/ssh/sshd_config
20180219164904:INFO:Found binary /usr/sbin/sshd
20180219164904:INFO:Reading ssh file /etc/ssh/sshd_config
20180219164904:INFO:Found open sshd version 7.2.-1p2
20180219164904:INFO:Testing option ChallengeResponseAuthentication
20180219164904:INFO:Option ChallengeResponseAuthentication supported
20180219164904:INFO:Testing option UsePAM
20180219164904:INFO:Testing option PAMAuthenticationViaKBDInt
20180219164904:INFO:Option PAMAuthenticationViaKBDInt not supported
20180219164904:INFO:Testing option KbdInteractiveAuthentication
20180219164904:INFO:Option KbdInteractiveAuthentication supported
20180219164904:INFO:Testing option GSSAPIAuthentication
20180219164904:INFO:Option GSSAPIAuthentication supported
20180219164904:INFO:Testing option GSSAPICleanupCredentials
20180219164904:INFO:Option GSSAPICleanupCredentials supported
20180219164904:INFO:Found config file /etc/ssh/ssh_config
20180219164904:INFO:Found binary /usr/bin/ssh
20180219164904:INFO:Reading ssh file /etc/ssh/ssh_config
20180219164904:INFO:Testing option GSSAPIAuthentication
20180219164905:INFO:Sshd does not support -o
20180219164905:INFO:Testing option GSSAPIDelegateCredentials
20180219164905:INFO:Sshd does not support -o
20180219164905:INFO:Running module hostname
20180219164905:INFO:Adding we1a1cs010a96 (fqdn we1a1cs010a96.ch2.ad.com) to /etc/hosts ip 127.0.0.1, removing we1a1cs010a96, we1a1cs010a96.ch2.ad.com, we1a1cs010a96, localhost.localdomain
20180219164905:INFO:Writing out updated /etc/hosts file
20180219164905:INFO:Found ifcfg file at /etc/sysconfig/network/ifcfg-eth0
20180219164905:INFO:Checking if DHCP Host...
20180219164905:INFO:Network manager is not enabled
20180219164905:INFO:Adding we1a1cs010a96 (fqdn we1a1cs010a96.ch2.ad.com) to /etc/hosts ip 127.0.0.1, removing we1a1cs010a96, we1a1cs010a96.ch2.ad.com, we1a1cs010a96, we1a1cs010a96.ch2.ad.com
20180219164905:WARNING:A resumable error occurred while processing the 'hostname' module
ERROR_BAD_COMMAND [code 0x00000016]

20180219164905:WARNING:ERROR_BAD_COMMAND [ERROR_BAD_COMMAND]

Stack Trace:
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djhostinfo.c:1286
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djhostinfo.c:1526
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djhostinfo.c:1064
20180219164905:INFO:Running module keytab
20180219164905:INFO:Reading krb5 file /etc/krb5.conf
20180219164905:INFO:Writing krb5 file /etc/krb5.conf
20180219164905:INFO:File /etc/krb5.conf modified
20180219164905:INFO:Reading krb5 file /tmp/likewisetmp6dNN77/etc/krb5.conf
20180219164905:INFO:Running module join
20180219172519:ERROR:eventlog:LwEvtWriteRecords():/builder/src-git/Platform/src/linux/eventlog/client/eventlog.c:524: Failed to write records. Error code [40185]

20180219172519:ERROR:LW_ERROR_ERRNO_EAGAIN [LW_ERROR_ERRNO_EAGAIN]

Stack Trace:
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:1304
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:652
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djmodule.c:355
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:857
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djauthinfo.c:1265
20180219172534:INFO:Domainjoin invoked with the join command (remaining arguments will be printed later):
20180219172534:INFO:    [domainjoin-cli]
20180219172534:INFO:    [--logfile]
20180219172534:INFO:    [/var/log/domain_join.log]
20180219172534:INFO:    [--loglevel]
20180219172534:INFO:    [info]
20180219172534:INFO:    [join]
20180219172534:INFO:Domainjoin invoked with option --ou OU=WE1-A1-CS01,OU=Alpha,OU=WE1,OU=DCTR,DC=CH2,DC=AD,DC=COM
20180219172534:INFO:Domainjoin invoked with 3 arg(s) to the join command:
20180219172534:INFO:    [ch2.ad.com]
20180219172534:INFO:    [-serv-chef-com-join]
20180219172534:INFO:    [<password>]
20180219172534:ERROR:Received error while querying lwsmd. [LW_ERROR_ERRNO_ECONNREFUSED]

Received error while querying lwsmd.

Stack Trace:
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:1304
/builder/src-git/Platform/src/linux/domainjoin/domainjoin-cli/src/main.c:549
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djmodule.c:254
/builder/src-git/Platform/src/linux/domainjoin/libdomainjoin/src/djdaemonmgr.c:68

**Comment by RBoulton-BT** [comment] 2018-02-21 12:53
Thanks for raising this, we have reproduced the resumable error ERROR_BAD_COMMAND on SLES12 and we'll be implementing a fix.

The other issue appears to be due to lwsmd not running.

Could you try running the following commands to confirm whether the PBIS services are running?

/opt/pbis/bin/lwsm list

ps -ef | grep lw

If there are no lwsmd or lw-container processes we'll need to determine why it's not running on this system.

**Comment by galbinasu** [comment] 2018-02-21 14:57
Thank you for the response! Here's the info you asked for:

**T2 instance:**
```
~ # /opt/pbis/bin/lwsm list
lwreg          running (container: 2969)
dcerpc         stopped
eventlog       running (container: 2990)
lsass          running (container: 3039)
lwio           running (container: 3022)
netlogon       running (container: 3007)
rdr            running (io: 3022)
reapsysl       running (container: 3060)
usermonitor    stopped
```


```
~ # ps -ef | grep lw
root      2956     1  0 13:52 ?        00:00:00 /opt/pbis/sbin/lwsmd --start-as-daemon
root      2969  2956  0 13:52 ?        00:00:00 lw-container lwreg
root      2990  2956  0 13:52 ?        00:00:00 lw-container eventlog
root      3007  2956  0 13:52 ?        00:00:00 lw-container netlogon
root      3022  2956  0 13:52 ?        00:00:00 lw-container lwio
root      3039  2956  0 13:52 ?        00:00:00 lw-container lsass
root      3060  2956  0 13:52 ?        00:00:00 lw-container reapsysl
root      4050  2259  0 13:53 pts/0    00:00:00 grep lw
```

**X1 instance**
```
~ # /opt/pbis/bin/lwsm list
lwreg          running (container: 3266)
dcerpc         stopped
eventlog       running (container: 3340)
lsass          running (container: 3553)
lwio           running (container: 3479)
netlogon       running (container: 3410)
rdr            running (io: 3479)
reapsysl       dead
usermonitor    stopped
```

```
~ # ps -ef | grep lw
root       3199      1  0 14:32 ?        00:00:00 /opt/pbis/sbin/lwsmd --start-as-daemon
root       3266   3199  0 14:32 ?        00:00:00 lw-container lwreg
root       3340   3199  0 14:32 ?        00:00:00 lw-container eventlog
root       3410   3199  0 14:32 ?        00:00:00 lw-container netlogon
root       3479   3199  0 14:32 ?        00:00:00 lw-container lwio
root       3553   3199  0 14:32 ?        00:00:00 lw-container lsass
root       3643   3199  0 14:32 ?        00:00:00 lw-container reapsysl
root       4066   3955  0 14:36 pts/0    00:00:00 grep lw
```

The difference seems to be with reapsysl being dead.

```
~ # /opt/pbis/bin/lwsm start reapsysl
Starting service: reapsysl
Error: LW_ERROR_SERVICE_UNRESPONSIVE (41203)
The service is not responding to requests
```

The service stays dead even after a reboot, with unknown pbis status
```
~ # pbis status
LSA Server Status:

Compiled daemon version: 8.5.7.385
Packaged product version: 8.5.385.1
Uptime:        0 days 0 hours 2 minutes 58 seconds

[Authentication provider: lsa-activedirectory-provider]

	Status:        Unknown
	Mode:          Unknown
```

**Comment by RBoulton-BT** [comment] 2018-02-27 10:54
The fix for resumable error has been merged so it will be part of the next scheduled release, hopefully before the end of March.

Back onto the other issue:

The reapsysl service isn't a core component so the fact it's not running shouldn't cause an impact. 

We could remove this from the equation by disabling it for now.

/opt/pbis/bin/regshell set_value [HKEY_THIS_MACHINE\\Services\\reapsysl] Autostart 0

service lwsmd restart

and then try the join again.

**Comment by rbest-bt** [comment] 2018-03-19 14:54
8.6.0 has been released and is available for download

**Closed** 2018-06-04 12:14 UTC
Labels: bug
