### ISSUE TITLE
Unable to Join Domain - Ubuntu 18.04

### ISSUE THREAD

**Issue by vBrit** [BeyondTrust/pbis-open#316] opened 2021-08-12 14:13 UTC
**Version**: 9.1.055
**OS/Distro**: Ubuntu desktop 18.04 - minimal install
**Issue/Impact**:
Unable to Join Domain. 
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
Fresh install on Ubuntu 18.04, minimal install. On same L2 segment as a pair of Domain Controllers. These are my default for DNS. I can ping the Domain i.e. ping lab.domain.com and it resolves to a DC. I can do a nslookup and it displays all the DC's.

 **1. systemctl status lwsmd.service**
   mfa-admin@lab-mfa:~$ systemctl status lwsmd.service
   lwsmd.service - BeyondTrust AD Bridge Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-08-11 18:02:44 EDT; 15h ago
 Main PID: 4258 (lwsmd)
    Tasks: 101 (limit: 4664)
   CGroup: /system.slice/lwsmd.service
           ├─4258 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─4271 lw-container lwreg
           ├─4293 lw-container eventlog
           ├─4310 lw-container netlogon
           ├─4325 lw-container lwio
           ├─4342 lw-container lsass
           └─4362 lw-container reapsysl

Aug 11 18:10:43 lab-mfa lsass[4342]: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -17653
Aug 11 18:10:43 lab-mfa lsass[4342]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider')
Aug 11 18:16:59 lab-mfa lsass[4342]: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -17653
Aug 11 18:16:59 lab-mfa lsass[4342]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider')
Aug 11 18:23:21 lab-mfa lsass[4342]: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -17653
Aug 11 18:23:21 lab-mfa lsass[4342]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider')
Aug 12 09:18:52 lab-mfa lsass[4342]: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -17653
Aug 12 09:18:52 lab-mfa lsass[4342]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider')
Aug 12 09:28:20 lab-mfa lsass[4342]: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -17653
Aug 12 09:28:20 lab-mfa lsass[4342]: [lsass] Failed to run provider specific request (request code = 8, provider = 'lsa-activedirectory-provider')
lines 1-24/24 (END)
 2. /opt/pbis/bin/lwsm list
 mfa-admin@lab-mfa:~$ /opt/pbis/bin/lwsm list
lwreg          running (container: 4271)
dcerpc         stopped
eventlog       running (container: 4293)
lsass          running (container: 4342)
lwio           running (container: 4325)
netlogon       running (container: 4310)
rdr            running (io: 4325)
reapsysl       running (container: 4362)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
mfa-admin@lab-mfa:~$ domainjoin-cli query           

Error: LW_ERROR_ACCESS_DENIED [code 0x00009cde]

Incorrect access attempt

 4. pbis status
LSA Server Status:

Compiled daemon version: 9.1.0.551
Packaged product version: 9.1.551.2
Uptime:        0 days 15 hours 48 minutes 36 seconds

[Authentication provider: lsa-activedirectory-provider]

        Status:        Unknown
        Mode:          Unknown

 5. /opt/pbis/bin/enum-users
 TotalNumUsersFound: 0
 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach [log]([lsass.log](https://github.com/BeyondTrust/pbis-open/files/6976004/lsass.log))

**Output/Error**:

**Steps to Reproduce**:
 1. install command
wget https://github.com/BeyondTrust/pbis-open/releases/download/9.1.0/pbis-open-9.1.0.551.linux.x86_64.deb.sh
chmod u+x pbis-open-9.1.0.551.linux.x86_64.deb.sh 
./pbis-open-9.1.0.551.linux.x86_64.deb.sh

 2. Domainjoin command
mfa-admin@lab-mfa:~$ sudo domainjoin-cli join lab-domain.com administrator

 3. Command that returns issue
Joining to AD Domain:   lab-domain.com
With Computer DNS Name: lab-mfa.lab-domain.com

administrator@LAB-DOMAIN.com's password: 

Error: LW_ERROR_DOMAIN_IS_OFFLINE [code 0x00009cb9]**

**Comment by rbest-bt** [comment] 2021-11-05 17:21
This is normally caused by a blocked port. Have a look at the troubleshooting guide for steps to test.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge

**Closed by rbest-bt** 2021-11-05 17:21 UTC
