### ISSUE TITLE
PBIS lost connection to domain, no AD user authentication

### ISSUE THREAD

**Issue by internetfloozy** [BeyondTrust/pbis-open#171] opened 2018-11-01 13:39 UTC
**Version**: 8.0.1.2029
**OS/Distro**: Ubuntu server 16.04
**Issue/Impact**: lost AD authentication
*Note: replace content with your own*
When reporting an issue it's important that we have as much detail as you can provide. The following is a list of commands to check.
 1. systemctl status lwsmd.service
lwsmd.service - LSB: Start and Stop PBIS Service Manager
   Loaded: loaded (/etc/init.d/lwsmd; bad; vendor preset: enabled)
   Active: active (running) since Thu 2018-11-01 10:29:39 ADT; 2min 23s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4403 ExecStop=/etc/init.d/lwsmd stop (code=exited, status=0/SUCCESS)
  Process: 4507 ExecStart=/etc/init.d/lwsmd start (code=exited, status=0/SUCCESS)
    Tasks: 111
   Memory: 15.0M
      CPU: 596ms
   CGroup: /system.slice/lwsmd.service
           ├─4543 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─4556 lw-container lwreg
           ├─4575 lw-container eventlog
           ├─4591 lw-container netlogon
           ├─4606 lw-container lwio
           ├─4623 lw-container lsass
           └─4645 lw-container reapsysl

Nov 01 10:29:39 gnservicesu02 lwsmd[4507]:  * Starting PBIS Service Manager: lwsmd
Nov 01 10:29:39 gnservicesu02 /opt/pbis/sbin/lwsmd[4543]: Logging started
Nov 01 10:29:39 gnservicesu02 lwreg[4556]: Logging started
Nov 01 10:29:39 gnservicesu02 eventlog[4575]: Logging started
Nov 01 10:29:39 gnservicesu02 netlogon[4591]: Logging started
Nov 01 10:29:39 gnservicesu02 lwio[4606]: Logging started
Nov 01 10:29:39 gnservicesu02 lsass[4623]: Logging started
Nov 01 10:29:39 gnservicesu02 reapsysl[4645]: Logging started
Nov 01 10:29:39 gnservicesu02 lwsmd[4507]:    ...done.
Nov 01 10:29:39 gnservicesu02 systemd[1]: Started LSB: Start and Stop PBIS Service Manager.

 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 4556)
dcerpc         stopped
eventlog       running (container: 4575)
lsass          running (container: 4623)
lwio           running (container: 4606)
netlogon       running (container: 4591)
rdr            running (io: 4606)
reapsysl       running (container: 4645)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
Error: LW_ERROR_PASSWORD_MISMATCH [code 0x00009c56]
The password is incorrect for the given account

 4. pbis status
LSA Server Status:
Compiled daemon version: 8.0.1.2029
Packaged product version: 8.0.2029.67662
Uptime:        0 days 0 hours 3 minutes 36 seconds
[Authentication provider: lsa-activedirectory-provider]
        Status:        Unknown
        Mode:          Unknown

 5. /opt/pbis/bin/enum-users
TotalNumUsersFound: 0

 6. attach logs
  auth.log
Nov  1 10:29:49 gnservicesu02 sshd[4676]: Invalid user username from 127.0.0.1
Nov  1 10:29:49 gnservicesu02 sshd[4676]: input_userauth_request: invalid user username  [preauth]
Nov  1 10:29:49 gnservicesu02 sshd[4676]: Postponed keyboard-interactive for invalid user username  from 127.0.0.1 port 50738 ssh2 [preauth]
Nov  1 10:29:51 gnservicesu02 sshd[4678]: pam_unix(sshd:auth): check pass; user unknown
Nov  1 10:29:51 gnservicesu02 sshd[4678]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=127.0.0.1

**Output/Error**:

Also, running update-dns I get:
Failed to update DNS.  The password is incorrect for the given account

but never prompted for an actual password.

There was a reboot done to this server Sunday night and after reboot logging in with AD account no longer works. Compared config files to other working servers and everything matches up.

**Comment by rbest-bt** [comment] 2018-11-01 14:48
On domainjoin query, LW_ERROR_PASSWORD_MISMATCH means the computers password does not match the Active Directory object. This could be caused by many things.

Rejoin the domain to fix the computer account password.

**Comment by internetfloozy** [comment] 2018-11-01 15:06
Already tried that, I get this error.

Error: LW_ERROR_INVALID_MESSAGE [code 0x00009c46]

The Inter Process message is invalid

**Comment by rbest-bt** [comment] 2018-11-01 15:48
Try removing the adcache file, restarting lwsmd and joining the domain again

` rm /var/lib/pbis/db/lsass-adcache.filedb.*`

**Comment by internetfloozy** [comment] 2018-11-01 15:51
rm: cannot remove '/var/lib/pbis/db/lsass-adcache.filedb.*': No such file or directory

permission denied when cd to /var/lib/pbis/db (it is set too 700)

**Comment by rbest-bt** [comment] 2018-11-01 17:01
After the upgrade can you rejoin the domain?

**Comment by internetfloozy** [comment] 2018-11-01 17:30
No after upgrade domainjoin-cli

Error: LW_ERROR_INVALID_MESSAGE [code 0x00009c46]
The Inter Process message is invalid

**Comment by rbest-bt** [comment] 2019-09-25 18:28
Did you have any luck getting this to work?

**Comment by rbest-bt** [comment] 2021-11-08 19:53
Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge

**Closed by rbest-bt** 2021-11-08 19:53 UTC
