### ISSUE TITLE
Regression: update-dns no longer working in Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by NdK73** [BeyondTrust/pbis-open#147] opened 2018-08-06 07:50 UTC
**Version**: 8.6.0.427 amd64
**OS/Distro**: Ubuntu desktop 18.04
**Issue/Impact**:
 1. systemctl status lwsmd.service
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/lib/systemd/system/lwsmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-08-06 09:32:14 CEST; 3min 54s ago
  Process: 922 ExecStart=/opt/pbis/sbin/lwsmd --start-as-daemon (code=exited, status=0/SUCCESS)
 Main PID: 978 (lwsmd)
    Tasks: 371 (limit: 4915)
   CGroup: /system.slice/lwsmd.service
           ├─ 978 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1029 lw-container lwreg
           ├─1085 lw-container eventlog
           ├─1139 lw-container netlogon
           ├─1192 lw-container lwio
           ├─1247 lw-container lsass
           └─1327 lw-container reapsysl

ago 06 09:32:13 str957-254 /opt/pbis/sbin/lwsmd[978]: Logging started
ago 06 09:32:13 str957-254 lwreg[1029]: Logging started
ago 06 09:32:13 str957-254 eventlog[1085]: Logging started
ago 06 09:32:13 str957-254 netlogon[1139]: Logging started
ago 06 09:32:14 str957-254 lwio[1192]: Logging started
ago 06 09:32:14 str957-254 lsass[1247]: Logging started
ago 06 09:32:14 str957-254 reapsysl[1327]: Logging started
ago 06 09:32:14 str957-254 systemd[1]: Started BeyondTrust PBIS Service Manager.
ago 06 09:32:15 str957-254 lsass[1247]: [lsass] Domain 'xxxxxxx' is now offline
ago 06 09:33:14 str957-254 lsass[1247]: [lsass] Domain 'xxxxxxx is now online

 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 1029)
dcerpc         stopped
eventlog       running (container: 1085)
lsass          running (container: 1247)
lwio           running (container: 1192)
netlogon       running (container: 1139)
rdr            running (io: 1192)
reapsysl       running (container: 1327)
usermonitor    stopped

 3. /opt/pbis/domainjoin-cli query
(note that the path in the template misses the 'bin/' part)
Name = str957-254
Domain = PERSONALE.xxxxxxxxx
Distinguished Name = CN=STR957-254,OU=Computer,OU=Str00957-DIFA,OU=Dsa.Auto,DC=personale,DC=xxxxxxxx,DC=xxxxxx,DC=xx

 4. pbis status
LSA Server Status:

Compiled daemon version: 8.6.0.427
Packaged product version: 8.6.427.243473
Uptime:        0 days 0 hours 7 minutes 8 seconds

[Authentication provider: lsa-activedirectory-provider]

	Status:        Online
	Mode:          Un-provisioned
	Domain:        PERSONALE.xxxxxx
	Domain SID:    S-1-5-21-2162351890-1506888927-3107636301
	Forest:        xxxxxx
	Site:          xxxxxx
	Online check interval:  300 seconds
	[Trusted Domains: 9]

	[Domain: PERSONALE]

		DNS Domain:       personale.xxxxx
		Netbios name:     PERSONALE
		Forest name:      xxxxx
		Trustee DNS name: 
		Client site name: xxxxx
		Domain SID:       S-1-5-21-2162351890-1506888927-3107636301
		Domain GUID:      00000000-0000-0000-0000-000000000000
		Trust Flags:      [0x0019]
		                  [0x0001 - In forest]
		                  [0x0008 - Primary]
		                  [0x0010 - Native]
		Trust type:       Up Level
		Trust Attributes: [0x0000]
		Trust Direction:  Primary Domain
		Trust Mode:       In my forest Trust (MFT)
		Domain flags:     [0x0001]
		                  [0x0001 - Primary]

		[Domain Controller (DC) Information]

			DC Name:              DCRPERSONALE01.personale.xxxxxxxxx
			DC Address:           xxxxxxx
			DC Site:              xxxxxxxxxx
			DC Flags:             [0x000031fc]
			DC Is PDC:            no
			DC is time server:    yes
			DC has writeable DS:  yes
			DC is Global Catalog: yes
			DC is running KDC:    yes
[Other domains in forest follow]

 5. /opt/pbis/bin/enum-users
Trust me, that would be 'a bit' too big... (~100k users).

 6. attach logs
  - /opt/pbis/bin/lwsm set-log-target -p lsass -  file /tmp/lsass.log
  - /opt/pbis/bin/lwsm set-log-level -p lsass - debug
  - attach log
No useful info.

**Output/Error**:
# /opt/pbis/bin/update-dns
Failed to update DNS.  No name servers could be reached.
Retry using --dnsserver option

**Steps to Reproduce**:
Just upgrade a joined Ubuntu 16.04LTS to 18.04LTS (or do a fresh install). update-dns stops working :(
Same machine, same address, same join procedure (I install using a script), different behaviour.
Probably Ubuntu changed something network-wise?

**Comment by rbest-bt** [comment] 2018-08-07 14:29
This was caused by an Ubuntu change in how they do DNS resolution. For now we added the --dnsserver option. With that option you can point to the dnsserver you want the record added to.

**Comment by NdK73** [comment] 2018-08-07 16:41
Does not work. Possibly our AD config is uncommon, but even giving the same IP used by update-dns in 16.04 fails in 18.04 :(

**Comment by Steffan-Ravn** [comment] 2018-08-10 08:54
Hi, I can confirm that we face the exact same problem here. We also tried the `--dnsserver` option, but to no avail, it still fails. I also have to admit that our AD setup is probably a bit uncommon, but it worked on Ubuntu 16.04.

**Comment by Steffan-Ravn** [comment] 2018-08-10 12:42
We have a DNS-server that redirects the requests to our Active Directory DNS-server, I've tried both and here are the outputs from debug I get.

Without `--dnsserver`:
> sudo /opt/pbis/bin/update-dns --loglevel debug
> 20180810143028:VERBOSE:0x7fe984295740:[DNSGetNameServers() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:229] Querying DNS for SOA Record for zone [adm-106005.adm.c.sdu.dk]
> 20180810143028:VERBOSE:0x7fe984295740:[DNSGetNameServers() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:249] SOA record not found [h_errno:4]
> 20180810143028:VERBOSE:0x7fe984295740:[DNSGetNameServers() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:229] Querying DNS for SOA Record for zone [adm.c.sdu.dk]
> 20180810143028:VERBOSE:0x7fe984295740:[DNSGetNameServers() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:249] SOA record not found [h_errno:4]
> 20180810143028:VERBOSE:0x7fe984295740:[DNSGetNameServers() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:229] Querying DNS for SOA Record for zone [c.sdu.dk]
> 20180810143028:VERBOSE:0x7fe984295740:[DNSBuildNameServerList() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:927] Adding Name Server [sdu-vdc0f.c.sdu.dk]
> 20180810143028:INFO:0x7fe984295740:[main() /builder/src-git/Platform/src/linux/lwdns/tools/lw-update-dns/main.c:282] Attempting to update name server [sdu-vdc0f.c.sdu.dk]
> 20180810143028:ERROR:0x7fe984295740:[main() /builder/src-git/Platform/src/linux/lwdns/tools/lw-update-dns/main.c:293] Failed to open connection to Name Server [sdu-vdc0f.c.sdu.dk]. [Error code:-2]
> Failed to update DNS.  No name servers could be reached.
> Retry using --dnsserver option

With our global dnsserver:
> sudo /opt/pbis/bin/update-dns --dnsserver 10.220.2.5 --loglevel debug
> 20180810142948:INFO:0x7f4eb90d9740:[main() /builder/src-git/Platform/src/linux/lwdns/tools/lw-update-dns/main.c:282] Attempting to update name server [10.220.2.5]
> 20180810142948:VERBOSE:0x7f4eb90d9740:[DNSTCPOpen() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnssock.c:146] Hostname:10.220.2.5
> 20180810142948:VERBOSE:0x7f4eb90d9740:[DNSTCPOpen() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnssock.c:148] IPV4 Address:10.220.2.5
> 20180810142948:INFO:0x7f4eb90d9740:[DNSUpdateSecure() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:588] Attempting DNS Update (in-secure)
> 20180810142948:INFO:0x7f4eb90d9740:[DNSUpdateCreateARUpdateRequest() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:818] Adding IP Address [10.85.12.16] to DNS Update request
> 20180810142948:ERROR:0x7f4eb90d9740:[main() /builder/src-git/Platform/src/linux/lwdns/tools/lw-update-dns/main.c:324] Failed to update Name Server [10.220.2.5]. [Error code:9504]
> Failed to update DNS. Error code [42700].
> Retry using --dnsserver option

With our AD-dnsserver:
> sudo /opt/pbis/bin/update-dns --dnsserver 10.144.5.25 --loglevel debug
> 20180810142959:INFO:0x7f1ed2b36740:[main() /builder/src-git/Platform/src/linux/lwdns/tools/lw-update-dns/main.c:282] Attempting to update name server [10.144.5.25]
> 20180810142959:VERBOSE:0x7f1ed2b36740:[DNSTCPOpen() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnssock.c:146] Hostname:10.144.5.25
> 20180810142959:VERBOSE:0x7f1ed2b36740:[DNSTCPOpen() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnssock.c:148] IPV4 Address:10.144.5.25
> 20180810142959:INFO:0x7f1ed2b36740:[DNSUpdateSecure() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:588] Attempting DNS Update (in-secure)
> 20180810142959:INFO:0x7f1ed2b36740:[DNSUpdateCreateARUpdateRequest() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:818] Adding IP Address [10.85.12.16] to DNS Update request
> 20180810142959:ERROR:0x7f1ed2b36740:[main() /builder/src-git/Platform/src/linux/lwdns/tools/lw-update-dns/main.c:324] Failed to update Name Server [10.144.5.25]. [Error code:9009]
> Failed to update DNS. Error code [42700].
> Retry using --dnsserver option

**Comment by NdK73** [comment] 2018-08-10 12:42
Here it is.
I took the IP of the DNS server from the update log of another machine, still at 16.04, so I'm quite sure it's correct.
```
root@str957-253:~# /opt/pbis/bin/update-dns --dnsserver x.x.x.x --loglevel debug
20180810143855:INFO:0x7f73f4a0b740:[main() /builder/src-git/Platform/src/linux/lwdns/tools/lw-update-dns/main.c:282] Attempting to update name server [x.x.x.x]
20180810143855:VERBOSE:0x7f73f4a0b740:[DNSTCPOpen() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnssock.c:146] Hostname:x.x.x.x
20180810143855:VERBOSE:0x7f73f4a0b740:[DNSTCPOpen() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnssock.c:148] IPV4 Address:x.x.x.x
20180810143855:INFO:0x7f73f4a0b740:[DNSUpdateSecure() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:588] Attempting DNS Update (in-secure)
20180810143855:INFO:0x7f73f4a0b740:[DNSUpdateCreateARUpdateRequest() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:818] Adding IP Address [y.y.y.y] to DNS Update request
20180810143855:ERROR:0x7f73f4a0b740:[main() /builder/src-git/Platform/src/linux/lwdns/tools/lw-update-dns/main.c:324] Failed to update Name Server [x.x.x.x]. [Error code:9009]
Failed to update DNS. Error code [42700].
Retry using --dnsserver option
```

**Comment by rbest-bt** [comment] 2018-08-10 12:51
> Error code [42700].

I see this error when targeting a server that does not have the zone for the record you are trying to add. Can you confirm the exact server that is maintaining the zone?

**Comment by NdK73** [comment] 2018-08-10 12:54
Yes. But on 16.04 if I specify --dnsserver using the same IP it would autodetect, it **fails**!

**Comment by rbest-bt** [comment] 2018-08-10 17:31
We're getting 8.7.0 wrapped up now. We'll try and have another pass and see if we can address the problems in 18.04 directly

**Comment by NdK73** [comment] 2018-08-21 09:09
Just upgraded pbis-open to 8.7.0.478, but still no change.

**Comment by RBoulton-BT** [comment] 2018-08-21 09:58
The log message "Failed to update Name Server [x.x.x.x]. [Error code:9009]" indicates the DNS server returned the error code 9009.

```
DNS_ERROR_RCODE_NOTAUTH
9009 (0x2331)
DNS server not authoritative for zone.
```

This appears to be saying the DNS server you are trying to use is not authoritative. It may be worth double checking which DNS servers are authoritative for your DNS zone you're trying to use and retrying.

**Comment by NdK73** [comment] 2018-08-21 10:51
From 16.04 machine (updated to pbis-open 8.7.0.478):
```
# /opt/pbis/bin/update-dns --loglevel debug
20180821123639:VERBOSE:0x7f57c62c0700:[DNSGetNameServers() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:229] Querying DNS for SOA Record for zone [my.long.machine.name]
20180821123639:VERBOSE:0x7f57c62c0700:[DNSGetNameServers() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:249] SOA record not found [h_errno:4]
20180821123639:VERBOSE:0x7f57c62c0700:[DNSGetNameServers() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:229] Querying DNS for SOA Record for zone [long.machine.name]
20180821123639:VERBOSE:0x7f57c62c0700:[DNSGetNameServers() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:249] SOA record not found [h_errno:4]
20180821123639:VERBOSE:0x7f57c62c0700:[DNSGetNameServers() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:229] Querying DNS for SOA Record for zone [machine.name]
20180821123639:VERBOSE:0x7f57c62c0700:[DNSBuildNameServerList() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsparser.c:927] Adding Name Server [adserver.machine.name]
20180821123639:INFO:0x7f57c62c0700:[main() /builder/src-git/Platform/src/linux/lwdns/tools/lw-update-dns/main.c:282] Attempting to update name server [adserver.machine.name]
20180821123639:VERBOSE:0x7f57c62c0700:[DNSTCPOpen() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnssock.c:146] Hostname:adserver.machine.name
20180821123639:VERBOSE:0x7f57c62c0700:[DNSTCPOpen() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnssock.c:148] IPV4 Address:123.45.67.89
20180821123639:INFO:0x7f57c62c0700:[DNSUpdateSecure() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:588] Attempting DNS Update (in-secure)
20180821123639:INFO:0x7f57c62c0700:[DNSUpdateCreateARUpdateRequest() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:818] Adding IP Address [123.45.69.87] to DNS Update request
20180821123639:INFO:0x7f57c62c0700:[DNSUpdateCreateARUpdateRequest() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:818] Adding IP Address [192.168.1.219] to DNS Update request
20180821123639:INFO:0x7f57c62c0700:[DNSUpdateSecure() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:654] DNS Update (in-secure) succeeded
A record successfully updated in DNS
```
Followed by other messages trying to update info for the second network card.
Note that it succeeded updating with a connection to adserver.machine.name (123.45.67.89).
Too bad that, **from the same machine**:
```
# /opt/pbis/bin/update-dns --loglevel debug --dnsserver 123.45.67.89
20180821123728:INFO:0x7f6aea159700:[main() /builder/src-git/Platform/src/linux/lwdns/tools/lw-update-dns/main.c:282] Attempting to update name server [123.45.67.89]
20180821123728:VERBOSE:0x7f6aea159700:[DNSTCPOpen() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnssock.c:146] Hostname:137.204.25.213
20180821123728:VERBOSE:0x7f6aea159700:[DNSTCPOpen() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnssock.c:148] IPV4 Address:137.204.25.213
20180821123728:INFO:0x7f6aea159700:[DNSUpdateSecure() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:588] Attempting DNS Update (in-secure)
20180821123728:INFO:0x7f6aea159700:[DNSUpdateCreateARUpdateRequest() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:818] Adding IP Address [137.204.51.32] to DNS Update request
20180821123728:INFO:0x7f6aea159700:[DNSUpdateCreateARUpdateRequest() /builder/src-git/Platform/src/linux/lwdns/lwdns/dnsupdate.c:818] Adding IP Address [192.168.1.219] to DNS Update request
20180821123728:ERROR:0x7f6aea159700:[main() /builder/src-git/Platform/src/linux/lwdns/tools/lw-update-dns/main.c:324] Failed to update Name Server [123.45.67.89]. [Error code:9009]
Failed to update DNS. Error code [42700].
Retry using --dnsserver option
```
Note that the authoritative DNS is **not** on the same network as the client machine, and the client machine does have two IP addresses (the private one is relative to a closed network not managed by AD, might be the reason for error 9009?).
I'll look for another machine with only one network card.

**Comment by Steffan-Ravn** [comment] 2018-08-21 10:56
What about [Error code:9504]?

**Comment by RBoulton-BT** [comment] 2018-08-21 12:17
That ones more vague, DNS error, check rcode.

You may find out more by looking at a packet capture of the DNS update attempt.

**Comment by Steffan-Ravn** [comment] 2018-08-22 11:50
I'll look into that when I have the time.

**Comment by cah-josephgeorge** [comment] 2018-08-31 16:03
Encountering this issue as well. Installed pbis-open to a vanilla ubuntu 16.04 and 18.04 AWS images. The 16.04 instance was able to update dns, 18.04 is not.

**Comment by NdK73** [comment] 2018-10-08 13:13
Just tested: if I manually edit /opt/resolv.conf to use the AD controllers, the update works.
Might be useful to know, at least as temporary workaround.

**Comment by cah-josephgeorge** [comment] 2019-01-10 13:57
Any update? Tried with 8.8.0.506, update still fails. Using the the work around given by NdK73 works for me, but I'd rather not update files maintained by the system.

**Comment by rbest-bt** [comment] 2019-01-10 16:16
This issue has not been addressed yet

**Comment by mctunes** [comment] 2019-10-29 17:22
This still appears to be an issue in 9.1.0.551 on a vanilla 18.04.3 LTS installation, same log messages as above comments.

**Comment by true64gurus** [comment] 2021-03-08 17:10
I am using latest release 9.1.0.551 on Ubuntu 18.04.5 LTS , same error as above. Nothing from workarounds worked. 
Appreciate any feedback. ?

**Comment by rbest-bt** [comment] 2021-11-08 18:56
Active Directory Bridge Enterprise has addressed this. Please upgrade to Active Directory Bridge Enterprise. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge

**Closed by rbest-bt** 2021-11-08 18:56 UTC
Labels: type: fix
