### ISSUE TITLE
Intermittent authentication problems through forest trusts

### ISSUE THREAD

**Issue by wmalcolm** [BeyondTrust/pbis-open#151] opened 2018-08-10 08:02 UTC
**Version**: 8.6.0.427
**OS/Distro**: Amazon Linux 2018.x, Red Hat Enterprise Linux 7.x
**Issue/Impact**:

Hello,

**NOTE: This looks like it may be related to https://github.com/BeyondTrust/pbis-open/issues/136 and https://github.com/BeyondTrust/pbis-open/issues/148, please advise if this is the case).**

We have a forest trust setup with Domain A and Domain B. Both are separate forests and are forest-root domains.
Domain C is a child domain of Domain B . So Domain B and Domain C have parent-child trusts. Users from Domain C are trying to access resources in Domain A;
 
The below issues have been observed across multiple separate sets of domains and implementations using the above mentioned operating systems.
 
* Users in domain A and B can access Amazon Linux and Red Hat Enterprise Linux systems running PBISO consistently.
* Users in domain C intermittently fail to login, once the failures begin, they will remain constant until the following command is executed on the affected system:
  * `/opt/pbis/bin/enum-groups --level 1`
* SSH logs under /var/log/secure indicate the user does not exist during the issue e.g.:
  * `Aug 9 15:26:58 ip-x-x-x-x sshd[16327]: Failed keyboard-interactive/pam for invalid user <child_domain>\\<user> from x.x.x.x port 57532 ssh2`
  * `Aug 9 15:26:58 ip-x-x-x-x sshd[16327]: Postponed keyboard-interactive for invalid user <child_domain>\\\\<user> from x.x.x.x port 57532 ssh2 [p reauth]`
* PBIS tools indicate the user does not exist at this time:
  * `$ /opt/pbis/bin/find-user-by-name <child_domain>\\<user> Failed to locate user. Error code 40008 (LW_ERROR_NO_SUCH_USER). No such user`
* After running enum-groups we can locate the user and SSH access is restored
* We’re also seeing an issue with trust users disappearing from the OS whilst logged in e.g. (related?) enum-groups also resolves this:
  * `whoami: cannot find name for user ID <user_id>`

lsass debug logs are attached (with private identifiers removed, please let me know if you require any further troubleshooting information and I'd be happy to provide it).

[lsass.log](https://github.com/BeyondTrust/pbis-open/files/2277067/lsass.log)

**Output/Error**:
`Failed to locate user. Error code 40008 (LW_ERROR_NO_SUCH_USER). No such user`

**Steps to Reproduce**:
 1. Setup trust as indicated above, issue is intermittent

**Comment by RBoulton-BT** [comment] 2018-08-10 16:36
It's interesting you're getting errors about Domain C being unknown. 

20180727142518:DEBUG:lsass:LsaDmpMustFindDomain():lsass/server/auth-providers/ad-open-provider/lsadm.c:1437: Do not know about domain 'DOMAINC'
20180727142518:DEBUG:lsass:LsaDmpQueryDomainInfoInternal():lsass/server/auth-providers/ad-open-provider/lsadm.c:2034: Error code: 40044 (symbol: LW_ERROR_NO_SUCH_DOMAIN)

Do you know if this happens all the time or only during the outages?
Also, approximately how often does this happen?

I'll try setting up a local environment to see if I can reproduce it.

From your description I believe the PBISO workstations are joined to Domain A?

**Comment by rbest-bt** [comment] 2018-08-10 19:19
> Users in domain C intermittently fail to login

To reproduce this issue I would like to know which domain the system is joined to. Are you joined to A and logging in with a user from C?

**Comment by wmalcolm** [comment] 2018-08-11 06:17
>  Do you have any Sites configured and/or RODCs?

Domain A is an [AWS Directory Service](https://aws.amazon.com/directoryservice/) running Microsoft AD, this system only supports Default-First-Site-Name so a single site there, and no RODCs. Domain B and C do not use RODCs for the trusts, however they can have additional sites as they usually are a more standard implementation of Microsoft AD.

> From your description I believe the PBISO workstations are joined to Domain A?

This is correct.

> To reproduce this issue I would like to know which domain the system is joined to. Are you joined to A and logging in with a user from C?

This is correct.

> Do you know if this happens all the time or only during the outages?

I'll check this and get back to you, uncertain offhand as we don't have debug logging on by default.

> Also, approximately how often does this happen?

Currently 5~ separate implementations that are experiencing this issue on a daily basis.

**Comment by RBoulton-BT** [comment] 2018-08-14 14:38
I've setup my lab to emulate this scenario however I haven't experienced any issues yet.

Does the command "pbis status" return the correct domain trust relationships? 
Do you get any domains reporting offline in the output of "pbis status"?

**Comment by flavioelawi** [comment] 2018-08-14 14:54
To reply to the request from 4 days ago, i'm attaching a debug log file with redacted domain names.
[](url)
The domain in the logfiles are 

DOMAINA
DOMAINB
DOMAINC

[lsass_successful.log](https://github.com/BeyondTrust/pbis-open/files/2287435/lsass_successful.log)

**Comment by RBoulton-BT** [comment] 2018-08-14 14:59
It looks like you're still getting errors resolving domainc. 

Could you try running get-dc-list for your domains to confirm PBIS can find the DCs?
e.g.
/opt/pbis/bin/get-dc-list domainc.domainb.net

**Comment by flavioelawi** [comment] 2018-08-14 15:00
Sorry I forgot to specify, the log is from a Successful login from a user in the DOMAINC to a machine joined to DOMAINA

**Comment by flavioelawi** [comment] 2018-08-14 15:14
[DOMAINA\user@ngyzyjizzgrmy2u ~]$ /opt/pbis/bin/get-dc-list domainc.domainb.net
Got 25 DCs:
===========
DC 1: Name = 'DCX.domainc.domainb.net', Address = 'x.x.x.x'
DC 2: Name = 'DCX.domainc.domainb.net', Address = 'x.x.x.x'
DC 3: Name = 'DCX.domainc.domainb.net', Address = 'x.x.x.x'
DC 4: Name = 'DCX.domainc.domainb.net', Address = 'x.x.x.x'
DC 5: Name = 'DCX.domainc.domainb.net', Address = 'x.x.x.x'
DC 6: Name = 'DCX.domainc.domainb.net', Address = 'x.x.x.x'
DC 7: Name = 'DCX.domainc.domainb.net', Address = 'x.x.x.x'
DC 8: Name = 'DCX.domainc.domainb.net', Address = 'x.x.x.x'
DC 9: Name = 'DCX.domainc.domainb.net', Address = 'x.x.x.x'
DC 10: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 11: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 12: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 13: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 14: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 15: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 16: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 17: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 18: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 19: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 20: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 21: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 22: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 23: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 24: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'
DC 25: Name = 'DXC.domainc.domainb.net', Address = 'x.x.x.x'

one of these Domain controllers is in /opt/pbis/bin/pbis-status output, under the DOMAINC "Domain Controller (DC) Information"

**Comment by cboutilier-bt** [comment] 2018-08-15 17:09
We have seen these types of issues in cases where there were intermittent DNS issues.

**Comment by cboutilier-bt** [comment] 2018-08-16 12:41
During the outages, does the output of pbis status report any of the domains offline? 
During a period where it is working, does the output of pbis status report any of the domains offline? 

Can you also confirm that pbis status displays the correct trust relationships?

**Comment by RBoulton-BT** [comment] 2018-08-20 12:49
One of our engineers dug into the log files some more and we believe he may have located the log messages that may help you identify the root cause of your issue.

`20180727142756:DEBUG:lsass:AD_DsGetDcName():lsass/server/auth-providers/ad-open-provider/adnetapi.c:1328: Failed to get dc name information for DOMAINC at WIN-12SPMM791Q0.domaina.removed.com (error 1355)`

This line indicates we are performing a call to DsrGetDCName (https://msdn.microsoft.com/en-us/library/cc237231.aspx) to your DC WIN-12SPMM791Q0.domaina.removed.com.  

According to the log, this is resulting in a 1355 return code:
```
ERROR_NO_SUCH_DOMAIN

1355 (0x54B)

The specified domain either does not exist or could not be contacted.
```

This is what results in us marking DOMAINC as being unavailable. 

This makes us believe your Domain Controller in DomainA may be having intermittent DNS issues locating trusted domain DOMAINC.

**Comment by wmalcolm** [comment] 2018-08-21 04:12
Thanks for the input, we're investigating this avenue (first checking connectivity to all of DCs, perhaps some of them are not contactable from this segment of the network) and will post back here.

**Comment by Cchokri97** [comment] 2019-03-04 07:33
Hello all,
Concerning authentication across trusted domain 
We have 2 domains one for servers and one for users and a trusted one way relation is established between the 2 forests. 
My question!
To make my authentication working does the client must access directly  to the users domain or it can connect over the trusted link?
How firewalls have to be configured about client access. 
Our configuration work now only if ports are opened from client to users domain and to servers domain too. 
When we closed ports from client to users domain only cached local users can connect
Thank you for your help!

**Comment by rbest-bt** [comment] 2019-06-03 18:29
We would need a lot more information about your setup. In general this should work as long as the computer can resolve anything it needs.

**Closed** 2019-09-25 18:30 UTC
