### ISSUE TITLE
can't login after locked screen

### ISSUE THREAD

**Issue by mmiat** [BeyondTrust/pbis-open#74] opened 2017-10-23 11:55 UTC
**Version**: 8.5.4.334
**OS/Distro**: Ubuntu desktop 16.04 - gnome desktop

after i've locked screen (for lunch) i can't login any more, i've to reboot

**Comment by rbest-bt** [comment] 2017-10-24 17:16
We are aware of some issues gdm and logins. Can you get me the syslog at the time of the failed login?

**Comment by mmiat** [comment] 2017-10-25 08:23
I've found similar problem here: #22 and #53 
I still not have logs, I'll send you later

this is my "/opt/pbis/bin/config --dump" output, maybe it could be useful:

> AllowDeleteTo ""
AllowReadTo ""
AllowWriteTo ""
MaxDiskUsage 104857600
MaxEventLifespan 90
MaxNumEvents 100000
DomainSeparator "\\"
SpaceReplacement "^"
EnableEventlog false
SaslMaxBufSize 16777215
Providers "ActiveDirectory"
DisplayMotd false
PAMLogLevel "error"
UserNotAllowedError "Access denied"
AssumeDefaultDomain true
CreateHomeDir true
CreateK5Login true
SyncSystemTime true
TrimUserMembership true
LdapSignAndSeal false
LogADNetworkConnectionEvents true
NssEnumerationEnabled true
NssGroupMembersQueryCacheOnly true
NssUserMembershipQueryCacheOnly false
RefreshUserCredentials true
CacheEntryExpiry 14400
DomainManagerCheckDomainOnlineInterval 300
DomainManagerUnknownDomainCacheTimeout 3600
MachinePasswordLifespan 2592000
ServicePrincipalName "host"
MemoryCacheSizeCap 0
HomeDirForceLowercase false
HomeDirPrefix "/home"
HomeDirTemplate "%H/%U"
RemoteHomeDirTemplate ""
HomeDirUmask "022"
LoginShellTemplate "/bin/bash"
SkeletonDirs "/etc/skel"
UserDomainPrefix "ANTEA.BOGUS"
DomainManagerIgnoreAllTrusts false
DomainManagerIncludeTrustsList
DomainManagerExcludeTrustsList
RequireMembershipOf
Local_AcceptNTLMv1 true
Local_HomeDirTemplate "%H/local/%D/%U"
Local_HomeDirUmask "022"
Local_LoginShellTemplate "/bin/sh"
Local_SkeletonDirs "/etc/skel"
UserMonitorCheckInterval 1800
LsassAutostart true
EventlogAutostart true
BlacklistDC

**Comment by rbest-bt** [comment] 2017-10-25 11:51
22 was an issue in regards to samba - Are you using samba?
53 is specifically the machine tgt not updating - since a reboot fixes your issue I don't believe this is the same problem

When you are locked out, can you get in as root or an admin account to check the logs?

Try '/opt/pbis/bin/lwsm list' to confirm the services are running

**Comment by mmiat** [comment] 2017-10-26 07:38
syslog:

> Oct 26 07:40:03 an-nb06270 lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328360 (Message: Preauthentication failed)
Oct 26 07:40:03 an-nb06270 lsass: [lsass] The cached machine account password was rejected by the DC.

**Comment by ParadingLunatic** [comment] 2017-11-01 15:33
I'm also having similar issues.  Checking the syslog I'm also getting the same preauthentication failed and The cached machine account password was rejected by the DC.  I have attempted to leave and rejoin the domain but no matter what I do when I try both, I get the error:

Error: LW_ERROR_PASSWORD_MISMATCH [code 0x00009c56]

The password is incorrect for the given account

I've tried rebooting.  Doesn't fix the problem.  I can login while the network isn't connected or while I'm not on the same network as my AD server, but the second it connects it fails.

**Comment by ParadingLunatic** [comment] 2017-11-02 16:51
Also just to mention, I've had PBIS installed and running for a good several months and had no issues until now.  Not sure why suddenly this problem is coming up.  doing a pbis status everything looks normal.  It sees my domain is online, sees my DC's and the GC's etc.  Here's the version info that is installed.

Compiled daemon version: 8.5.4.334
Packaged product version: 8.5.334.8

**Comment by jessecrayston** [comment] 2017-11-06 17:08
Experiencing this issue with Version: 8.5.6.375

Syslog messages at the time:
`
Nov  3 16:13:17 **hostname** lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328360 (Message: Preauthentication failed)
Nov  3 16:13:17 **hostname** lsass: [lsass] Failed to authenticate user (name = '**username**') -> error = 40022, symbol = LW_ERROR_PASSWORD_MISMATCH, client pid = 30130
`

**Comment by mmiat** [comment] 2017-11-14 10:46
i don't know if linked with this issues, but every morning i login and after a few seconds it loses connection with domain, the user:group of files are with uid and not the name, the terminal lose the username before @, if i give "/opt/pbis/bin/domainjoin-cli query" i have:

> Error: LW_ERROR_ACCESS_DENIED [code 0x00009cde]
Incorrect access attempt

after rebooting 5-6 times it start working

**Comment by mmiat** [comment] 2017-11-14 11:19
if I do:
/opt/pbis/bin/lwsm restart lsass
domainjoin-cli leave
domainjoin-cli join MYDOMAIN MYACCOUNT
it restarts working
I'll see if/when it stops again

**Comment by rbest-bt** [comment] 2017-11-14 12:47
Can you upgrade to 8.5.6? There was another issue with trust enumeration that was addressed in 8.5.5 and I want to make sure your not getting that issue also.

**Comment by mmiat** [comment] 2017-11-14 12:50
I've the last version
i've upgraded It One week ago

Il 14 novembre 2017 13:47:32 CET, rbest-bt <notifications@github.com> ha scritto:
>Can you upgrade to 8.5.6? There was another issue with trust
>enumeration that was addressed in 8.5.5 and I want to make sure your
>not getting that issue also.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/BeyondTrust/pbis-open/issues/74#issuecomment-344248757

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by mmiat** [comment] 2017-11-16 08:06
it has worked 2 days, this morning again

**Comment by mmiat** [comment] 2017-11-16 08:53
if this can help (from start to restart):

> Nov 14 08:50:41 an-nb06270 gdm-launch-environment]: pam_unix(gdm-launch-environment:session): session opened for user gdm by (uid=0)
Nov 14 08:50:41 an-nb06270 systemd-logind[876]: New session c1 of user gdm.
Nov 14 08:50:41 an-nb06270 systemd: pam_unix(systemd-user:session): session opened for user gdm by (uid=0)
Nov 14 08:50:47 an-nb06270 polkitd(authority=local): Registered Authentication Agent for unix-session:c1 (system bus name :1.34 [gnome-shell --mode=gdm], object path /org/f
reedesktop/PolicyKit1/AuthenticationAgent, locale it_IT.UTF-8)
Nov 14 08:50:47 an-nb06270 realmd[2051]: Loaded settings from: /usr/lib/realmd/realmd-defaults.conf /usr/lib/realmd/realmd-distro.conf
Nov 14 08:50:47 an-nb06270 realmd[2051]: holding daemon: startup
Nov 14 08:50:47 an-nb06270 realmd[2051]: starting service
Nov 14 08:50:47 an-nb06270 realmd[2051]: connected to bus
Nov 14 08:50:47 an-nb06270 realmd[2051]: released daemon: startup
Nov 14 08:50:47 an-nb06270 realmd[2051]: claimed name on bus: org.freedesktop.realmd
Nov 14 08:50:53 an-nb06270 gdm-password]: pam_unix(gdm-password:session): session opened for user ANTEA\m.miat by (uid=0)
Nov 14 08:50:53 an-nb06270 systemd-logind[876]: New session 1 of user ANTEA\m.miat.
Nov 14 08:50:53 an-nb06270 systemd: pam_unix(systemd-user:session): session opened for user ANTEA\m.miat by (uid=0)
Nov 14 08:50:55 an-nb06270 su[2110]: No passwd entry for user 'ANTEAm.miat'
Nov 14 08:50:55 an-nb06270 su[2110]: FAILED su for ANTEAm.miat by root
Nov 14 08:50:55 an-nb06270 su[2110]: - ??? root:ANTEAm.miat
Nov 14 08:50:56 an-nb06270 gnome-keyring-daemon[2095]: The Secret Service was already initialized
Nov 14 08:50:56 an-nb06270 gnome-keyring-daemon[2095]: The PKCS#11 component was already initialized
Nov 14 08:50:56 an-nb06270 gnome-keyring-daemon[2095]: The SSH agent was already initialized
Nov 14 08:51:00 an-nb06270 polkitd(authority=local): Registered Authentication Agent for unix-session:1 (system bus name :1.69 [/usr/bin/gnome-shell], object path /org/free
desktop/PolicyKit1/AuthenticationAgent, locale it_IT.UTF-8)
Nov 14 08:51:41 an-nb06270 gnome-keyring-daemon[2095]: couldn't allocate secure memory to keep passwords and or keys from being written to the disk
Nov 14 08:51:41 an-nb06270 gnome-keyring-daemon[2095]: asked to register item /org/freedesktop/secrets/collection/login/2, but it's already registered
Nov 14 08:51:41 an-nb06270 gnome-keyring-daemon[2095]: asked to register item /org/freedesktop/secrets/collection/login/2, but it's already registered
Nov 14 08:51:48 an-nb06270 realmd[2051]: quitting realmd service after timeout
Nov 14 08:51:48 an-nb06270 realmd[2051]: stopping service

**Comment by mmiat** [comment] 2017-11-23 09:00
the problem appears every morning at the first boot, after 4-5 reboots it works

**Comment by rbest-bt** [comment] 2017-11-23 13:09
What is the result of:
> /opt/pbis/bin/config --show MachinePasswordLifespan

**Comment by mmiat** [comment] 2017-11-24 07:59
> /opt/pbis/bin/config --show MachinePasswordLifespan

>dword
2592000
local policy

**Comment by mmiat** [comment] 2017-12-11 08:50
this morning if i do:
`/opt/pbis/bin/lwsm restart lsass`
i've the error

> Stopping service: lsass
Error: LW_ERROR_ACCESS_DENIED (40158)
Incorrect access attempt

**Comment by rbest-bt** [comment] 2017-12-11 18:37
It seems like something is changing the computer objects password in Active Directory - maybe another computer using the same object/hostname? Domainjoins would fix this as it's setting a new machine password for your computer and the AD computer object. This would be temporary until it gets reset again by the other object.

Try changing your hostname and issuing a new domainjoin. This should create a new AD computer object. I would also try using the --ou option and try a different location.

**Comment by mmiat** [comment] 2017-12-13 08:38
i've make "leave" of the workstation, deleted it from AD objects, and rejoin
same problem
not changed hostname, for now

**Comment by mmiat** [comment] 2017-12-15 08:58
another client now has the same issue, after i've upgraded pbis from 8.5.4.334 to 8.5.7.385

**Comment by dustin-Optfit** [comment] 2018-01-02 15:25
I have the same issue on one of my computers. I can login when it first starts up but after that my password doesn't work.

**Comment by mmiat** [comment] 2018-01-10 08:27
this morning at system startup i cant' login
after 4 reboots it works

some logs:

> Jan 10 09:05:59 an-nb06270 lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328378 (Message: Client 'AN-NB
06270$@ANTEA.BOGUS' not found in Kerberos database)
Jan 10 09:06:11 an-nb06270 lsass: message repeated 2 times: [ [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -176532
8378 (Message: Client 'AN-NB06270$@ANTEA.BOGUS' not found in Kerberos database)]

**Comment by Criticize** [comment] 2018-01-23 15:12
I am having the same exact issues with RDP login to the GDM, post 8.5.7.385 update. 

**Operating System:** CentOS 6.8
**Physical Server**

The only way I've been able to get my users into the machine other then rebooting it, is logging in either through SSH or RDP as root, then entering in the following commands.

`root ~ # sudo su -`
`root ~ # su - username` _(of user who is having the issue)_
`username ~ # exit`

Then I ask them to login and they are good to go for a few days, eventually it occurs again after a week or so.

**Comment by mmiat** [comment] 2018-01-30 09:17
I've same problem also in a Mac with OSX. maybe an issue related to server and not to client?

**Comment by mmiat** [comment] 2018-02-15 08:15
again, after a month or more, one of the clients has disconnected and i've to leave and rejoin

**Comment by mmiat** [comment] 2018-02-27 08:34
this is what i found in /var/log/syslog this morning:

> Feb 27 08:51:53 an-nb06414 lsass: [lsass] The cached machine account password was rejected by the DC.
Feb 27 08:51:53 an-nb06414 lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328360 (Message: Preauthentication failed)

**Comment by mmiat** [comment] 2018-02-27 10:27
i've searched for a long this morning.... and i found many things that are not clear to me....

1. [here](https://www.youtube.com/watch?v=oNCzh3dkdBM) the author says to edit /etc/pam.d/common-session 
2. [here](https://forum.zentyal.org/index.php?topic=24191.0) the author says to add some packages that pbis doesn't install as libpam-winbind libnss-winbind krb5-config, [here](https://wiki.zentyal.org/wiki/Authenticating_Linux_client_against_Samba) i found to install also sssd heimdal-clients msktutil
3. [here](https://ubuntuforums.org/showthread.php?t=1455924) the author says to edit hostname
4. in PBIS_Installation_Guide.pdf i found to edit nsswitch.conf and keep only "hosts: files dns"

are all these configurations needed ? thanks

**Comment by mmiat** [comment] 2018-02-28 13:38
today again after the lunch, when it requests password the system cant authenticate

> Feb 28 13:43:40 an-nb06414lnx lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328228 (Message: Cannot con                  tact any KDC for realm 'ANTEA.BOGUS')
Feb 28 13:43:40 an-nb06414lnx lsass: [lsass] Domain 'antea.bogus' is now offline
Feb 28 13:43:42 an-nb06414lnx lsass: [lsass] Failed to sync system time [error code: 9502]
Feb 28 13:43:42 an-nb06414lnx lsass: [lsass] Failed to sync system time [error code: 9502]
Feb 28 13:48:27 an-nb06414lnx lsass: [lsass] Domain 'antea.bogus' is now online
Feb 28 13:48:27 an-nb06414lnx lsass: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1405] KRB5 Error code: -1765328377                   (Message: Server not found in Kerberos database)
Feb 28 13:57:13 an-nb06414lnx lsass: message repeated 13 times: [ [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1405]                   KRB5 Error code: -1765328377 (Message: Server not found in Kerberos database)]
Feb 28 13:57:13 an-nb06414lnx lsass: [lsass] Failed to authenticate user (name = 'ANTEA\kovalevskyy.vitaliy') -> error = 41738, symbol = LW_ERROR_KRB5KDC_ERR_S_PRINCIPAL_UN                  KNOWN, client pid = 3029

**Comment by rbest-bt** [comment] 2018-02-28 18:05
I think the issue is with your timesync. Try setting up your machine with the same ntp server your domain controllers are using. Then reissue a domainjoin with the --notimesync option:
> /opt/pbis/bin/domainjoin-cli join --notimesync domain.com adminuser

Is if the system improves

**Comment by mmiat** [comment] 2018-03-01 08:01
this morning user cant login, but if i login through ssh i can see the notebook is in domain
so i edited /usr/share/lightdm/lightdm.conf.d/50-unity-greeter.conf and add option greeter-show-manual-login=true so the user now can login inserting username by manual

**Comment by mmiat** [comment] 2018-03-02 08:19
CLIENT 1
this morning i cant login:
No passwd entry for user 'miatello.mauro'

tried to leave and rejoin
Error: ERROR_USER_EXISTS [code 0x00000524]

i deleted workstation account in my domain, rebooted, and joined with --notimesync

i also installed libpam-kwallet4 because after lock the screen remains black

monday we will see :)

CLIENT 2
this morning ok

**Comment by mmiat** [comment] 2018-03-14 12:41
nooo today again, returning from lunch

auth.log

> Mar 14 13:32:06 an-nb06414lnx compiz: [lsass-pam] [module:pam_lsass]pam_sm_authenticate error [login:ANTEA\kovalevskyy.vitaliy][error code:41738]
Mar 14 13:32:06 an-nb06414lnx compiz: pam_unix(unity:auth): authentication failure; logname= uid=2062025900 euid=2062025900 tty= ruser= rhost=  user=ANTEA\kovalevskyy.vitaliy
Mar 14 13:32:14 an-nb06414lnx compiz: [lsass-pam] [module:pam_lsass]pam_sm_authenticate error [login:ANTEA\kovalevskyy.vitaliy][error code:41738]
Mar 14 13:32:14 an-nb06414lnx compiz: pam_unix(unity:auth): authentication failure; logname= uid=2062025900 euid=2062025900 tty= ruser= rhost=  user=ANTEA\kovalevskyy.vitaliy

syslog
> Mar 14 13:32:06 an-nb06414lnx lsass: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1405] KRB5 Error code: -1765328377 (Message: Server not found in Kerberos database)
Mar 14 13:32:06 an-nb06414lnx lsass: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1405] KRB5 Error code: -1765328377 (Message: Server not found in Kerberos database)
Mar 14 13:32:06 an-nb06414lnx lsass: [lsass] Failed to authenticate user (name = 'ANTEA\kovalevskyy.vitaliy') -> error = 41738, symbol = LW_ERROR_KRB5KDC_ERR_S_PRINCIPAL_UNKNOWN, client pid = 2858
Mar 14 13:32:13 an-nb06414lnx lsass: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1405] KRB5 Error code: -1765328377 (Message: Server not found in Kerberos database)
Mar 14 13:32:14 an-nb06414lnx lsass: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1405] KRB5 Error code: -1765328377 (Message: Server not found in Kerberos database)
Mar 14 13:32:14 an-nb06414lnx lsass: [lsass] Failed to authenticate user (name = 'ANTEA\kovalevskyy.vitaliy') -> error = 41738, symbol = LW_ERROR_KRB5KDC_ERR_S_PRINCIPAL_UNKNOWN, client pid = 2858
Mar 14 13:33:43 an-nb06414lnx kernel: [15038.420462] asus_wmi: Unknown key 84 pressed
Mar 14 13:33:46 an-nb06414lnx lsass: GSS API error calling gss_init_sec_context(): majorStatus = 0x000d0000 (Unspecified GSS failure.  Minor code may provide more information), minorStatus = 0x96c73a06 (Client not found in Kerberos database)

**Comment by cboutilier-bt** [comment] 2018-03-14 13:56
Thank you for this information. We have been able to reproduce this in house and we are investigating it.

**Comment by mmiat** [comment] 2018-04-16 07:17
this morning error again

some logs from "journalctl -xe", i hope they could be useful:

> apr 16 08:34:43 an-nb06414lnx lightdm[1793]: pam_kwallet(lightdm:session): pam_kwallet: pam_sm_open_session
apr 16 08:34:43 an-nb06414lnx lightdm[1793]: pam_kwallet(lightdm:session): pam_kwallet: final socket path: /tmp/kwallet_ANTEA\kovalevskyy.vitaliy.socket
apr 16 08:34:43 an-nb06414lnx lightdm[1815]: pam_kwallet: could not execute kwalletd from /usr/bin/kwalletd
apr 16 08:34:43 an-nb06414lnx lightdm[1793]: pam_kwallet5(lightdm:session): pam_kwallet5: pam_sm_open_session
apr 16 08:34:43 an-nb06414lnx lightdm[1793]: pam_kwallet5(lightdm:session): pam_kwallet5: final socket path: /tmp/kwallet5_ANTEA\kovalevskyy.vitaliy.socket
apr 16 08:34:43 an-nb06414lnx lightdm[1817]: pam_kwallet5: could not execute kwalletd from /usr/bin/kwalletd5
apr 16 08:34:43 an-nb06414lnx org.ayatana.bamf[1896]: bamfdaemon start/running, process 1949
apr 16 08:34:44 an-nb06414lnx su[2019]: No passwd entry for user 'ANTEAkovalevskyy.vitaliy'
apr 16 08:34:44 an-nb06414lnx su[2019]: FAILED su for ANTEAkovalevskyy.vitaliy by root
apr 16 08:34:44 an-nb06414lnx su[2019]: - ??? root:ANTEAkovalevskyy.vitaliy
apr 16 08:34:44 an-nb06414lnx su[2019]: FAILED su for ANTEAkovalevskyy.vitaliy by root
apr 16 08:34:44 an-nb06414lnx su[2019]: - ??? root:ANTEAkovalevskyy.vitaliy
apr 16 08:34:44 an-nb06414lnx kernel: wlp3s0: authenticate with f0:99:bf:0d:98:38
apr 16 08:34:44 an-nb06414lnx wpa_supplicant[1008]: wlp3s0: SME: Trying to authenticate with f0:99:bf:0d:98:38 (SSID='an-ac' freq=2437 MHz)
apr 16 08:34:44 an-nb06414lnx NetworkManager[832]: <info>  [1523860484.2291] device (wlp3s0): supplicant interface state: scanning -> authenticating
apr 16 08:34:44 an-nb06414lnx kernel: wlp3s0: send auth to f0:99:bf:0d:98:38 (try 1/3)
apr 16 08:34:44 an-nb06414lnx wpa_supplicant[1008]: wlp3s0: Trying to associate with f0:99:bf:0d:98:38 (SSID='an-ac' freq=2437 MHz)
apr 16 08:34:44 an-nb06414lnx kernel: wlp3s0: authenticated
apr 16 08:34:44 an-nb06414lnx kernel: wlp3s0: associate with f0:99:bf:0d:98:38 (try 1/3)
apr 16 08:34:44 an-nb06414lnx NetworkManager[832]: <info>  [1523860484.2388] device (wlp3s0): supplicant interface state: authenticating -> associating
apr 16 08:34:44 an-nb06414lnx wpa_supplicant[1008]: wlp3s0: Associated with f0:99:bf:0d:98:38
apr 16 08:34:44 an-nb06414lnx kernel: wlp3s0: RX AssocResp from f0:99:bf:0d:98:38 (capab=0x1411 status=0 aid=25)
apr 16 08:34:44 an-nb06414lnx kernel: wlp3s0: associated
apr 16 08:34:44 an-nb06414lnx kernel: IPv6: ADDRCONF(NETDEV_CHANGE): wlp3s0: link becomes ready

it seems that the wifi connection is still not available and lsass failed to login and then hangs

**Comment by mmiat** [comment] 2018-04-17 09:06
today again, after a standby, even if upgraded pbis to 8.6.0

**Comment by mmiat** [comment] 2018-04-26 07:36
"/etc/init.d/lightdm restart" seems to fix

**Comment by mmiat** [comment] 2018-06-25 07:57
this morning again:

> giu 25 09:53:16 an-nb06380lnx lsass[1342]: [lsass] Domain 'antea.bogus' is now online
giu 25 09:53:21 an-nb06380lnx lsass[1342]: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328360
giu 25 09:53:21 an-nb06380lnx lsass[1342]: [lsass] The cached machine account password was rejected by the DC.
giu 25 09:53:21 an-nb06380lnx su[1996]: No passwd entry for user 'adminmauro'
giu 25 09:53:21 an-nb06380lnx su[1996]: FAILED su for adminmauro by mauro
giu 25 09:53:21 an-nb06380lnx su[1996]: - /dev/pts/8 mauro:adminmauro

restart didnt fix, i've to leave and rejoin
how to check cached machine account and eventually fix/reset/copy/manage it ?

**Comment by mmiat** [comment] 2018-08-27 07:32
this morning user cant login with error:

> Error: LW_ERROR_KRB5KDC_ERR_C_PRINCIPAL_UNKNOWN [code 0x0000a309]
Client not found in Kerberos database

after leave and join it works

**Comment by almightyju** [comment] 2018-09-05 16:29
I've just started getting this myself today and I don't know why. Just tried upgrading pbis-open and the initial login works and if I'm quick enough I can sudo open a terminal to check logs while logged in. In syslog I get this after the wireless connects to the network


> lsass: [lsass] Domain 'xcina.co.uk' is now online
> lsass: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1404] KRB5 Error code: -1765328377 (Message: Server not found in Kerberos database)
> lsass: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1404] KRB5 Error code: -1765328377 (Message: Server not found in Kerberos database)
> lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328378 (Message: Client 'REMOVED' not found in Kerberos database)
> lsass: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1404] KRB5 Error code: -1765328377 (Message: Server not found in Kerberos database)
> lsass: [LwKrb5InitializeUserLoginCredentials /builder/src-git/Platform/src/linux/lwadvapi/threaded/lwkrb5.c:1404] KRB5 Error code: -1765328377 (Message: Server not found in Kerberos database)
> lsass: [lsass] Failed to authenticate user (name = 'REMOVED') -> error = 41738, symbol = LW_ERROR_KRB5KDC_ERR_S_PRINCIPAL_UNKNOWN, client pid = 1961
> lsass: [LwKrb5GetTgtImpl /builder/src-git/Platform/src/linux/lwadvapi/threaded/krbtgt.c:346] KRB5 Error code: -1765328378 (Message: Client 'REMOVED' not found in Kerberos database)

I'll have to try rejoining the domain and see if it works

**Comment by rbest-bt** [comment] 2019-05-03 13:26
Give 9.0.1 a try and see if that addresses the issue

**Comment by mmiat** [comment] 2019-05-17 09:04
I'm updating all my clients, hope this fix
thanks

**Closed** 2019-09-13 17:43 UTC
Labels: bug
