### ISSUE TITLE
pbis only returning a subset of groups for some users

### ISSUE THREAD

**Issue by repudi8or** [BeyondTrust/pbis-open#11] opened 2016-12-20 21:32 UTC
This is similar to issue #8 however, it was discounted as different by the poster. Thus I have raised this issue as separate thread to track debug activity

Environment: Linux myserver 3.13.0-68-generic #111~precise1-Ubuntu SMP Fri Nov 6 18:17:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux 
PBIS vers: ii  pbis-open                        8.5.2.265                           Authentication services for Active Directory domains

Symptom: 
When the group_cache is working my user has 121 groups. 
$ id | tr ',' '\n' | wc -l
121
when it gets messed up i'm only seeing 17 groups from /opt/pbis/bin/list-groups-for-user myuser
$ id | tr ',' '\n' | wc -l
17

The issue is 100% reproducible.
I can introduce the problem by clearing the ad-cache and starting a new shell as myuser
sudo /opt/pbis/bin/ad-cache --delete-user --name myuser
list-groups then shows only a small subset of expected groups:
$ id | tr ',' '\n' | wc -l
16

I can get a fully populated group list if i do an authenticate-user and start a fresh shell:
/opt/pbis/bin/lsa authenticate-user --user myuser
$ id | tr ',' '\n' | wc -l
121

I see this in my log at time of "authenticate-user" :-
20161214045456:VERBOSE:lsass: The user group membership information for user MYDOMAIN\myuser does not match what is in the cache, because the cache contains 19 memberships, but the pac contains 113 memberships. The group membership now needs to be compared against LDAP.

upon "authenticate-user", lsass appears to refresh the group cache and all is working again. So the issue seems to occur on cold cache. Like maybe its not loading the groups on first reference after ad-cache-delete
issue seems to represent after a duration of time (i'm guessing after ad-cache TTL expiry)

**Comment by rob0r** [comment] 2016-12-21 01:44
Seeing the same behaviour on Ubuntu 12.04, 14.04, 16.04.
- Seen on the version available via the APT repo
`Compiled daemon version: 8.5.1.206
Packaged product version: 8.5.206.2564`

- Seen on https://github.com/BeyondTrust/pbis-open/releases/latest
`Compiled daemon version: 8.5.2.265
Packaged product version: 8.5.265.1`

An affected user
`id affecteduser | tr ',' '\n' | wc -l
22`

If the users group listing still contains the group they use to get SSH in, they can do:
`/opt/pbis/bin/lsa authenticate-user --user affecteduser`

if the users groups are lost to the point of not being able to SSH in, another user has to run:
`/opt/pbis/bin/enum-groups --level 1`

Following the above
`id affecteduser | tr ',' '\n' | wc -l
121`

It seems like some users are plagued by this.. Whilst others are not.. It doesn't seem to be the number of groups causing it - As we have an un-affected user with 129 groups.

**Comment by repudi8or** [comment] 2016-12-22 07:35
What further diagnostic can i take to figure out whats happening here ?

**Comment by RBoulton-BT** [comment] 2016-12-22 09:53
I believe some of this behavior may be expected.

When a user authenticates they receive a PAC in their Kerberos ticket, this contains a definitive list of group membership for the user which PBIS caches. By default PBIS uses the cache to query group membership and does not query AD when performing NSS related functions (id, getent passwd etc). I believe this is to reduce the load on AD. 

You can control this behavior with the NssGroupMembersQueryCacheOnly config setting. 

/opt/pbis/bin/config NssGroupMembersQueryCacheOnly false

Should disable this optimization and result in AD being queried for group entries.

**Comment by joshbaldock** [comment] 2016-12-22 11:04
I have tried the recommended NssGroupMembersQueryCacheOnly disabling, but im still seeing an issue for a user unable to login due to improper group membership representation.

On host where user is denied access due to invalid groups:
`admin@badhost:~$ /opt/pbis/bin/list-groups-for-user USER | grep '^Number'
Number of groups found for user 'USER' : 13`

On host where user is correctly allowed access due to correct groups:
`admin@goodhost:~$ /opt/pbis/bin/list-groups-for-user USER
Number of groups found for user 'USER' : 179`

Also while testing this running the above on the 'good' host, I have just seen it switch to having limited group lists also:
`admin@goodhost~$ /opt/pbis/bin/list-groups-for-user USER | grep '^Number'
Number of groups found for user 'USER' : 13`

So something seems inconsistent in the client caches or in the response processing of the client.

**Comment by RBoulton-BT** [comment] 2016-12-22 11:21
Sorry for the confusion, I wasn't saying this would fix the issue, I was trying to explain the discrepancies with group memberships after deleting the cache. 

Following an authentication the group memberships should be correct because we have the PAC, so if it's not we need to identify why we're failing to get this correctly.

In terms of gathering diagnostics, we include a perl script /opt/pbis/libexec/pbis-support.pl this runs the PBIS daemons in debug mode and can collect a support package. So for example you could run

/opt/pbis/libexec/pbis-support.pl -o -c

This runs in debug mode until you type "done <enter>"

So while running this In one console window, perform the failing logon test in another console window. This will generate a support pack in /tmp which will contain a lot of debug data. Some of this may be sensitive so you should be cautious attaching anything to this case.

**Comment by tapessur** [comment] 2016-12-23 15:53
I too have been plagued with this issue/bug and my **workaround** has been to clear the cache. I know this has been suggested before and confirmed not to work but there's a trick to it I've found.
After you clear the cache it's important you **DON'T** try to lookup the user's group memberships using tools like "id", "lsa", "list-groups-for-user" etc, but instead ask the user to authenticate. This seems to get the correct groups in the cache seeing that it uses the groups in the PAC of the kerberos ticket. When using tools like id or lsa, powerbroker uses a different method in getting the user's group membership (as RBoulton-BT suggests) and populates the cache. This method is probably where the bug is.

**Comment by joshbaldock** [comment] 2016-12-27 11:07
Thanks @tapessur for the tips, however we are still having issues with a particular user not being able to login, even after following your specific workaround instructions.

@RBoulton-BT I have performed a pbis-support capture and emailed the results to beyondtrust as instructed by the tool. Hopefully more details/clues lie within.

**Comment by joshbaldock** [comment] 2017-01-02 07:51
@RBoulton-BT - Just wondering if you received my pbis-support email and have been able to get any insight into what the issue may be?

**Comment by repudi8or** [comment] 2017-01-10 23:27
any update on this issue ? Its pretty annoying that it choses to drop my sudo group every new shell I make

**Comment by rbest-bt** [comment] 2017-01-11 13:12
@joshbaldock Yes we received the support pack and we'll have a look

**Comment by keithtyler** [comment] 2017-01-11 18:25
We are also having the issue. Any update on getting this fixed?

**Comment by RBoulton-BT** [comment] 2017-01-11 19:04
We're actively investigating this, unfortunately we can't reproduce this internally so we're relying on support packs from our community.

**Comment by repudi8or** [comment] 2017-01-12 03:40
Happy to assist with the diagnostic effort in any way. Please contact me directly if there is something i can do to facilitate this.

**Comment by dsekely** [comment] 2017-01-26 17:13
We are also having this issue.  It's only affecting access to samba shares

**Comment by RBoulton-BT** [comment] 2017-01-26 17:17
Quick update on this. We have been working with @joshbaldock and were able to reproduce the issue and are now preparing a fix ready for the 8.5.3 release which is scheduled for end of Q1.

**Comment by rbirkenhake** [comment] 2017-01-30 15:41
Great news!

Can you tell me, if this fix is only for better caching or even for better resolving the membership from AD?

Do you need additional support packs?

**Comment by RBoulton-BT** [comment] 2017-01-31 11:36
This fix resolves an issue where the list of groups PBIS identifies for users when querying AD can be incorrect when the user is also a member of distribution groups.

**Comment by VigneshVickyS** [comment] 2017-01-31 14:12
Even I'm facing the similar kind of issue, the user testuser1 is part of testgroup2 and also part of 150 AD groups, but when I logged into the offended Linux server execute the below command it says the user is only part of 72 groups.

 [root@TestServer109 tmp]# /opt/pbis/bin/list-groups-for-user testuser1 | wc -l
72

Then I tried to execute enum-group level -1 command which fixed the issue and I could see the user is part of all 152 groups.

enum group command: /opt/pbis/bin/enum-group --level -1

But Once I cleaned the cache or rebooted the machine, the issue occurred again. ( /opt/pbis/bin/ad-cache --delete-all).

Even Fresh installation doesn't fixed the issue on that machine. I've tried with different Pbis version, all have the same issue.

**Comment by RBoulton-BT** [comment] 2017-02-28 15:31
We uploaded a beta for 8.5.3 today with the proposed fix for this issue https://github.com/BeyondTrust/pbis-open/releases. Any feedback will be welcomed.

**Comment by KoZm0kNoT** [comment] 2017-03-21 12:43
I have downloaded and installed the newest 8.5.3 release (not a beta now). However, I am still having issues with group memberships that involve accounts from an AD trust. Specifically, I have joined an AD domain PrimaryDomain which has a trust to another domain TrustedDomain. I have added a sudoers drop-in file to grant root access to an account in TrustedDomain. This part works fine...I can logon as the TrustedDomain account and elevate that account to root with sudo.

I do not want to have to explicitly place user into the sudoers drop-in. I want to use a group account that has the user accounts as members and create a drop-in for the group.

However, if I remove the explicit account from the drop-in and instead create a drop-in for the group, the account is no longer able to be granted sudo permissions. If I examine the groups the TrustedDomain account belongs to I get "0":

```
[root@ip-10-22-13-249 ~]# /opt/pbis/bin/list-groups-for-user TRUSTEDDOMAIN\\someaccount
Number of groups found for user 'TRUSTEDDOMAIN\\someaccount' : 0
```

I used to see this behavior in the previous version if I cleared the cache and the group memeberships will all start returning no results, but the groups will mysteriously repopulate itself at some point during the day. Is there a way to initiate this or force a synchronization so all the groups are populated?

**Comment by KoZm0kNoT** [comment] 2017-03-29 12:35
bump

**Comment by RBoulton-BT** [comment] 2017-03-29 12:38
Hi, could you raise this as a new issue please, it will be a lot easier to track.

**Comment by rbest-bt** [comment] 2017-08-04 18:00
Closing this as cleanup/resolved as a fix was issued. If you are having issues in this regard please open a new issue.

**Closed by rbest-bt** 2017-08-04 18:00 UTC
Labels: bug
