### ISSUE TITLE
Corrupted Posix ACLs

### ISSUE THREAD

**Issue by Rgrassoa** [BeyondTrust/pbis-open#69] opened 2017-10-18 16:10 UTC
**Version**: 8.5.5.372
**OS/Distro**: Debian 8.9
**Issue/Impact**: using Samba 4.2 and Posix ACLs, the acls are corrupted when saving an MS-Office 2016 document
*Note: replace content with your own*

Hello,
I have this issue on two other physical machines : one with Debian 8.9 and Samba 4 , the other one with CentOS 7 and Samba 4. I have other machines with previous PBIS Open versions and samba 3.X where I do not have this issue. So in order to troubleshoot it, I created a new vm from scratch, installing Debian 8.9; then I added the APT repository and installed the package pbis-open. I setup PBIS Open with domainjoin-cli, which went seamlessly.
Then I setup Samba (configuration file below). Next, I create this /netdir, add some Posix ACLs : 
# file: netdir/
# owner: root
# group: root
user::rwx
user:xxxx1:rwx
user:xxxx2:rwx
user:xxxx3:rwx
user:xxxx4:rwx
group::r-x
mask::rwx
other::r-x
default:user::rwx
default:user:xxxx1:rwx
default:user:xxxx2:rwx
default:user:xxxx3:rwx
default:user:xxxx4:rwx
default:group::r-x
default:mask::rwx
default:other::r-x

Next, I go to Windows 7 : there, it is weird : 
- if I create a file with the notepad, modify the content and save it, the acls are correct
- if I create a file with MS-Word 2016 or MS-Excel 2016 (same if v2013) : just after having been created, the acls are fine : 

getfacl: Removing leading '/' from absolute path names
# file: netdir/tw9.docx
# owner: xxxx3
# group: domain^users
user::rwx
user:xxxx1:rwx
user:xxxx2:rwx
user:xxxx3:rwx
user:xxxx4:rwx
group::r--
mask::rwx
other::r--

but as soon as I modify it and save it, the acls are messed up : 

getfacl: Removing leading '/' from absolute path names
# file: netdir/tw9.docx
# owner: xxxx3
# group: domain^users
user::rwx
user:1230188368:rwx
group::r--
group:domain^users:r--
mask::rwx
other::r--

the user id 1230188368 does not exist : 
/opt/pbis/bin/find-user-by-id 1230188368
Failed to locate user.  Error code 40008 (LW_ERROR_NO_SUCH_USER).
No such user

_Any suggestion ? Any possible fix ?_

Here is smb.conf : 

[global]
   security = ADS
   workgroup = XXX
   realm = YYY
   machine password timeout = 0
   log level = 3
   debug pid = true
   log file = /var/log/samba/log.%m
   max log size = 1000000
[netdir]
   path = /netdir
   browseable = yes
   read only = no

**Comment by Rgrassoa** [comment] 2017-10-23 10:15
Just to be accurate : I created the Word or Excel  files from the Windows Explorer contextual menu : thus it was an operating system/file system operation, I did not create them from inside Word or Excel

**Comment by rbest-bt** [comment] 2018-02-09 19:52
I'm not able to reproduce this issue. Is this issue on both Centos 7 and Debian 8 or just Debian 8? Was the file modified as an AD user or as a user not in the domain? Is this only for word's .doc files or any files, like; txt, ppt, html, etc...?

**Comment by rbest-bt** [comment] 2018-02-12 15:17
I have discovered some issues around cache between pbis and samba. This can cause issues with creating/modifying files getting acls created with the old samba cache. I'm not sure if this is what your running into but it might be worth resetting both:
>/opt/pbis/bin/ad-cache --delete-all
> systemctl restart smb

**Comment by Rgrassoa** [comment] 2018-02-12 15:47
Thank you for taking care of this. I have a couple of things to do right now, I will get back to you and answer your questions in some hours.

Best regards


Robert Grasso | System engineer
T +33 (0)4 56 38 08 33 | F +33 (0)4 56 38 08 30

rgrasso@altair.com | www.altair.com <http://www.altair.com/>
Altair | Innovation Intelligence ®

**Comment by Rgrassoa** [comment] 2018-02-13 14:15
Hello,

Answering your questions : 
- question #2 : yes, the user modifying the files was belonging to our domain;
- the answers to the remaining two questions are in my first email opening this case, dating oct 18, 2017 : please read it back.

Apart from that; I restarted my Debian test vm, ran your commands : 
/opt/pbis/bin/ad-cache --delete-all
and
/etc/init.d/smb restart
/etc/init.d/nmb restart

on this Debian version, Samba services cannot be managed by Systemd.

Right now, I am not able to access my test shares with ACLs from Windows 7, but as I did not test this before applying your command, I cannot say for sure why I am having this issue. I will try to investigate a bit more.

This being said, I am surprised that you were not able to reproduce the issue, as to me it seems pretty consistent : each time we install PBIS Open with our conditions, we have the issue : could you share with me your test configurations, so that I compare yours with mine ? and maybe we will figure out what makes your configuration work ?

**Comment by danisowa** [comment] 2018-03-27 06:46
Hello, 
any news on this problem?
I have the same problem, when changing a office file on my samba share the file gets the following acls
# file: testfile.xlsx
# owner: testuser
# group: testgroup
user::rwx
user:1230188368:rwx
group::rwx

user is set to the id 1230188368 and before saving the file it was testuser

**Comment by rbest-bt** [comment] 2021-11-08 17:21
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge

**Closed by rbest-bt** 2021-11-08 17:21 UTC
