### ISSUE TITLE
Windows Home Folder does not get unmounted at logout

### ISSUE THREAD

**Issue by Steffan-Ravn** [BeyondTrust/pbis-open#10] opened 2016-12-19 14:18 UTC
Hi there

When users log in, they have their Active Directory home folders mounted under their userfolder, with this RemoteHomeDirTemplate:
"%H/%D/%U/M-Drive"
Whenever they logout, the share is NOT unmounted, this means that all the shares from multiple users are still mounted, after they logout and leave the machine.
I can't see a setting to control this in PowerBroker and unmount during logout works fine for other shares, which are mounted via PAM_MOUNT.
We are using the latest version of PowerBroker (8.5.2.265) on Ubuntu 16.04 with the standard Unity Desktop Environment.

Any help solving this issues is highly appreciated.

**Comment by rbest-bt** [comment] 2016-12-21 13:17
Working to reproduce this issue. I have confirmed that by design they should umount at logoff:

"On logoff, the network mount will be disconnected shortly after the users session end"

**Comment by rbest-bt** [comment] 2016-12-21 19:15
I have confirmed this issue. I see an umount after every second logout. After 6 logins I see that 4 mounts still mounted. 

At this time I do not have a work around or fix beside a creating a script to clean this up.

Thank you for bringing it to our attention.

**Comment by Steffan-Ravn** [comment] 2016-12-22 09:11
Wonderful to hear that it's not just in our environment. :)
Thanks for responding so quickly.

**Comment by jelayeb** [comment] 2017-09-26 07:12
Hi Steffan-Ravn

would you please explain how do you mount windows home dirs, in Linux with pbis-open.
are you mounting them as smb shares? do you use automounter for this? 
i want to have the same setup but i can not figured out. 

thanks in advance

**Comment by Steffan-Ravn** [comment] 2017-09-26 08:37
Hi @jelayeb 
I use the build-in mechanism in pbis-open for this, please refer to Example 3 on page 214 in this guide: [https://github.com/BeyondTrust/pbis-open/blob/master/reskit/pbis-open-installation-and-administration-guide.pdf](url)
Basically you can use the config-tool /opt/pbis/bin/config to set different settings, amongst other things the RemoteHomeDir, the local location and umask etc.

**Comment by jelayeb** [comment] 2017-10-06 11:14
thanks @Steffan-Ravn 
i'm familial with the pbis config tool, but i'm not with the windows domain, 
i can not figureout with path will be mounted is the normal user profile path or the Home Dir local path or the drive connect path, 
because currently our domain admins dont use those configs at all and they use group polices to manage users home dirs and other mountpoints. 
we tried to configure a Home Dir local path to drive k for testing on my domain account, and configured pbis to remotehomedir to /remote/%U/test and created that folder ofcourse on the linux machine. but nothing happend when the user logged in. 
it seems that i'm missing an essential step here 
if you could explain me the windows side would be great, just to know where and what to configure

Thanks

**Comment by Steffan-Ravn** [comment] 2017-10-09 11:17
Hi @jelayeb 
Okay, I must admit that I'm no Windows admin and here at my work we have a different group of people working with the Windows Server part of things, so I'll try my best to help.
The path that gets mounted is set here in the user profile on the server-side:
[http://1.bp.blogspot.com/-LfH2PyKLi_I/UX5yCL106EI/AAAAAAAACmw/m1SchDPGXLI/s1600/a.png](url)
It is not necessary to create the folder on the Linux Client but the remote folder you are trying to mount should exist beforehand. 
The user who logs in on the Linux Client of course also need to have at least read-rights on the folder you are trying to mount.

Hope this helps.

**Comment by jelayeb** [comment] 2017-10-10 14:50
after many tries, i found that i dont have samba client installed. then i did install it and then i can not log in into graphical mode anymore, and i found those errors whenever i login or switch to domain user . 
[453.3245468] CIFS VFS: cifs_mount failed w/return code = -126
it looks like permissions problems, but i tried this folder to give it everyone read/write permissions and the same error. 

any hints

**Comment by Steffan-Ravn** [comment] 2017-10-11 07:02
I have a suspicion that you are experiencing Kerberos issues. Is the Samba-server configured with Kerberos and does it work? Can you successfully do a manual mount of the share?

Lets say you are using a user called "user1" in a domain called "example.org" and mounting a share called "user1folder" at a server called "smb.example.org".

Make sure you have a Kerberos-ticket:
`kinit user1@EXAMPLE.ORG`

Ask for a Kerberos-ticket to a particular SMB-share:
`kvno cifs/smb.example.org@EXAMPLE`

Then connect with Kerberos to the particular share and server:
`smbclient -k //smb.example.org/user1folder `

Does this work for you?

**Comment by jelayeb** [comment] 2017-10-11 09:30
domainusers remote dirs are windows2012R2 not Samba, 
jaelayeb@wha1076s1:0[bash]~$kvno cifs/zha600FS-E/HomeDirsE01/JAELAYEB
kvno: Server not found in Kerberos database while getting credentials for cifs/zha600FS-E/HomeDirsE01/JAELAYEB@DOMAIN
jaelayeb@wha1076s1:0[bash]~$smbclient -k //zha600FS-E/HomeDirsE01/JAELAYEB
protocol negotiation failed: NT_STATUS_CONNECTION_RESET.

**Comment by Steffan-Ravn** [comment] 2017-10-11 09:57
It doesn't matter if it's a Windows or Linux SMB-share, the point is that the share and server has to be configured with Kerberos.
I can see your kvno-request is not correct, you should not include shares or paths in the request, in your case it should look something like this instead:
`kvno cifs/zha600FS-E@<DOMAIN>`

I don't know which Kerberos-realm (domain) the server belongs too, but you need to replace the "<DOMAIN>" part with the correct realm.

**Comment by rbest-bt** [comment] 2021-11-05 16:59
pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge

**Closed by rbest-bt** 2021-11-05 16:59 UTC
Labels: type: fix
