### ISSUE TITLE
PBIS not creating home directories from /etc/skel on fresh login from domain user.

### ISSUE THREAD

**Issue by hey-you-its-me** [BeyondTrust/pbis-open#117] opened 2018-03-22 23:14 UTC
**Version**: 8.5.2
**OS/Distro**: Oracle Enterprise Linux 7
**Issue/Impact**: 
Users are able to log in and get work done, but do not get the .bashrc and .bash_profile from /etc/skel. The directory is created and populated with some files, but not the ones from /etc/skel. Only happens on NFS-mounted directories, only happens on OEL7. Works fine on CentOS 6.9 with an NFS home directory.

Instead of pulling files form /etc/skel, it is pulling (or creating) from somewhere else. These files are created:

-bash-4.2$ ls -al
total 20
drwxr-xr-x.  5 USERNAME domain^users 4096 Mar 22 16:06 .
drwxr-xr-x. 53 root       root         4096 Mar 22 16:06 ..
drwxr-xr-x.  3 USERNAME domain^users 4096 Mar 22 16:06 .cache
drwxr-xr-x.  3 USERNAME domain^users 4096 Mar 22 16:06 .config
-rw-r--r--.  1 USERNAME domain^users   46 Mar 22 16:06 .k5login
drwxr-xr-x.  2 USERNAME domain^users 4096 Mar 22 16:06 .mozilla

Whereas /etc/skel has different files:

-bash-4.2$ ls -al /etc/skel
total 24
drwxr-xr-x.   3 root root   74 Nov 14 12:34 .
drwxr-xr-x. 143 root root 8192 Mar 22 14:46 ..
-rw-r--r--.   1 root root   18 Sep  5  2017 .bash_logout
-rw-r--r--.   1 root root  193 Sep  5  2017 .bash_profile
-rw-r--r--.   1 root root  231 Sep  5  2017 .bashrc
drwxr-xr-x.   4 root root   37 Nov 14 10:06 .mozilla

I should note, the .mozilla in the created home directory is empty. The .mozilla in /etc/skel has more things in it.

 1. systemctl status lwsmd.service
● lwsmd.service - BeyondTrust PBIS Service Manager
   Loaded: loaded (/usr/lib/systemd/system/lwsmd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2018-03-08 09:13:12 PST; 2 weeks 0 days ago
 Main PID: 1238 (lwsmd)
   CGroup: /system.slice/lwsmd.service
           ├─1238 /opt/pbis/sbin/lwsmd --start-as-daemon
           ├─1251 lw-container lwreg
           ├─1273 lw-container eventlog
           ├─1289 lw-container netlogon
           ├─1304 lw-container lwio
           ├─1323 lw-container lsass
           └─1365 lw-container reapsysl
 2. /opt/pbis/bin/lwsm list
lwreg          running (container: 1251)
dcerpc         stopped
eventlog       running (container: 1273)
lsass          running (container: 1323)
lwio           running (container: 1304)
netlogon       running (container: 1289)
rdr            running (io: 1304)
reapsysl       running (container: 1365)
usermonitor    stopped
 3. attach logs
Mar 22 10:43:36 HOSTNAME lsass[1323]: [lsass] Failed to create home directory for user (USERNAME), actual error 40249
Mar 22 10:43:36 HOSTNAME lsass[1323]: [lsass] Failed to create home directory for user (USERNAME), actual error 40052
Mar 22 10:43:36 HOSTNAME lsass[1323]: [lsass] Failed to open session for user (name = 'USERNAME') -> error = 40052, symbol = LW_ERROR_FAILED_CREATE_HOMEDIR, client pid = 19206

**Steps to Reproduce**:
1. Join domain
2. Set HomeDirTemplate to some directory that is an NFS mount
3. Set SkeletonDirs and Local_SkeletonDirs to "/etc/skel"
4. Sign in as a user who does not already have a populated homedir.
5. /etc/skel is not copied to the user's home directory. The home directory is created and is populated with other files that are not in /etc/skel

**Comment by hey-you-its-me** [comment] 2018-03-26 20:33
Just checked, the version of pbis-open that is working (on older servers) is 6.5.538, not 8.5.2. 8.5.2 does not work.

I'm also now getting different error messages despite not having changed anything. No more messages in /var/log/messages, where I was getting LW_ERROR_FAILED_CREATE_HOMEDIR earlier, but instead I'm getting the following in /var/log/secure:

Mar 26 13:14:12 HOSTNAME sshd[13691]: [lsass-pam] [module:pam_lsass]pam_sm_open_session failed [login:USERNAME][error code: 40052]

**Comment by rbest-bt** [comment] 2018-04-03 13:28
Could you try running SElinux in permissive mode and try again?

**Comment by hey-you-its-me** [comment] 2018-04-04 20:44
SELinux is in permissive mode.

I was able to work around this issue by adding the following line to `/etc/pam.d/sshd`:

```
session    required     pam_mkhomedir.so skel=/etc/skel
```

at a point in the file before lsass gets called. It's kind of a rigged solution and it would be nice if lsass didn't break when trying to create homedirs on NFS mounts, which is what _seems_ to be happening.

**Comment by MichaelBeatty** [comment] 2018-10-18 20:42
I'm experiencing this exact problem on a pair of RHEL 7.5 servers.  PBIS 8.7.0-478

lsass: [lsass] Failed to open session for user (name = 'username') -> error = 40052, symbol = LW_ERROR_FAILED_CREATE_HOMEDIR, client pid = 12301

**Comment by cklagenberg** [comment] 2020-04-29 11:06
I know this is old, but ran into the samme problem as MichaelBeatty.

/etc/pam.d/common-session was missing this line:
`session optional        pam_lsass.so`

pam-auth-update might fix it.
The root cause: making manually changes in pam.d configs.

**Comment by rbest-bt** [comment] 2021-11-08 19:50
Please upgrade to Active Directory Bridge Enterprise as we have introduced some fixes for this. If the issue still exists then please submit a ticket to our service team and we’ll have a look for you.

pbis-open will longer receive updates and will be archived. Closing all outstanding issues. Please consider BeyondTrust Active Directory Bridge for continued support.  
https://www.beyondtrust.com/privilege-management/active-directory-bridge

**Closed by rbest-bt** 2021-11-08 19:50 UTC
