### ISSUE TITLE
URGENT PLEASE - change Home folder mapping path MacOS

### ISSUE THREAD

**Issue by dbgbl** [BeyondTrust/pbis-open#224] opened 2019-07-04 15:44 UTC
**Version**: 9.0.1.525
**OS/Distro**: MacOS 10.14.5
**Issue/Impact**:
*Note: replace content with your own*
Very simple request I hope.

The default location for the local users created when connected to AD is Macintiosh HD/Users/local/DOMAIN

I would like to map that to anther directory.

How can I change this please. Urgent issue affecting my users.

many thanks

**Comment by rbest-bt** [comment] 2019-07-04 17:49
See the config option called HomeDirTemplate

>/opt/pbis/bin/config --detail HomeDirTemplate

**Comment by dbgbl** [comment] 2019-07-05 14:42
Hi rbtest, many thanks for the reply however that path does not exist in this version. Attached are screen shots of the folder structure and the four files containing HomeDir. I have found the file that contains a reference but it is not taking form some reason. Attached is the changed file with the new path to a separate volume. "/Volumes/HOMES/Folders

Any help will be gratefully received.

[lsassd.reg.zip](https://github.com/BeyondTrust/pbis-open/files/3363067/lsassd.reg.zip)

![Screen Shot 2019-07-05 at 09 33 28](https://user-images.githubusercontent.com/52541901/60725689-a6abc680-9f31-11e9-9e61-a1092d633c2e.png)
![Screen Shot 2019-07-05 at 09 33 11](https://user-images.githubusercontent.com/52541901/60725698-aad7e400-9f31-11e9-8d98-41bf1a274289.png)

**Comment by dmorash-BT** [comment] 2019-07-05 20:05
You should just need to set the HomeDirTemplate config value to represent the home dir path you want.  The CreateHomeDir and HomeDirPrefix config values are also relevant here.  

You can see all the supported config values by using `/opt/pbis/bin/config --list`, get details of them via `/opt/pbis/bin/config --details <setting>`, or check the [Config Reference Guide](https://github.com/BeyondTrust/pbis-open/wiki/docs/adb-config-tool-reference-guide.pdf) 

e.g. if I set HomeDirPrefix to "/adusers", and HomeDirTemplate to "%H/%D/%U" I'll get home directories like /adusers/mydomain/dmorash-bt

**Comment by dbgbl** [comment] 2019-07-05 21:39
Thanks for your help. I have changed it to the following in three places. Am I missing something as it does not seem to be taking?

"HomeDirPrefix" = {
    default = "/Volumes/HOMES/Folders"
    doc = "Prefix path for user's home directory. This value is used in place of the %H in the HomeDirTemplate setting. Value must be an absolute path."
}
"HomeDirTemplate" = {
    default = "%H/local/%D/%U"
    doc = "Format string for user's home directory path. This value can contain substitution string markers for HomeDirPrefix (%H), Domain (%D), and User (%U)."

**Comment by dmorash-BT** [comment] 2019-07-06 12:40
You said you changed this in three places which makes it sound like you are editing files to change this option.  You need to use the config tool to set options.  I would a) undo all the edits you made to files, b) set the option with the config tool, then c) verify that it is set how you want by using the config tool to show the values.

**Comment by dbgbl** [comment] 2019-07-08 17:51
I am using the following command to change it and the mac gets locked up when logging in as an AD user. Any ideas would really help. Running from the opt/pbis/bin directory

./config HomeDirPrefix default = "/Volumes/HOMES/Folders"

**Comment by dmorash-BT** [comment] 2019-07-08 18:24
It's likely the users home directory is not being created.  So you'll need to check that: 

1. Did the user's home directory get created and is it owned by that user?
2. Is the CreateHomeDir config option set to true?
3. Can root create that directory?
4. Check the logs for messages like "Failed to create home directory".  Usually the specific cause of that is found a bit earlier in the logs. 

Additionally just verifying that you want home directories to be `/Volumes/HOMES/Folders/<mydomain>/<user>` ?

**Comment by dmorash-BT** [comment] 2019-07-08 18:32
Ah, the problem is that you are using config incorrectly. That config command should be `./config HomeDirPrefix "/Volumes/HOMES/Folders"`   Once you set it, verify it is set how you want via `./config --details HomeDirPrefix`.

If after that it still isn't working, than verify the items in my previous reply.

**Comment by dbgbl** [comment] 2019-07-08 19:04
Thats's done it. Thank you for your help. We are working again with Mojave. Now to Catalina!!

**Comment by dmorash-BT** [comment] 2019-07-10 11:47
Glad to hear it. I'll close this issue.  Please open a new issue if you have any more problems.

**Closed** 2019-07-10 11:50 UTC
Labels: question
